# Generated by Django 4.2.27 on 2025-12-05 04:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Opportunity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="商机名称")),
                (
                    "customer_name",
                    models.CharField(max_length=100, verbose_name="客户姓名"),
                ),
                (
                    "customer_company",
                    models.CharField(max_length=200, verbose_name="客户公司"),
                ),
                (
                    "customer_org",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="客户组织/部门"
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("CONTACT", "接触阶段"),
                            ("REQ_ANALYSIS", "需求分析"),
                            ("INITIATION", "客户立项"),
                            ("BIDDING", "招采阶段"),
                            ("DELIVERY", "交付实施"),
                            ("AFTER_SALES", "售后阶段"),
                        ],
                        default="CONTACT",
                        max_length=20,
                        verbose_name="当前阶段",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "进行中"),
                            ("WON", "赢单"),
                            ("LOST", "输单"),
                            ("SUSPENDED", "挂起"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                        verbose_name="商机状态",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=12, verbose_name="预计金额"
                    ),
                ),
                (
                    "signed_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="新签合同金额",
                    ),
                ),
                (
                    "gross_profit",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=12, verbose_name="回款毛利"
                    ),
                ),
                (
                    "revenue",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="确认收入金额",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "expected_sign_date",
                    models.DateField(blank=True, null=True, verbose_name="预计签约时间"),
                ),
                (
                    "is_confirmed_by_sales",
                    models.BooleanField(default=False, verbose_name="销售已确认生效"),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_opportunities",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="登记人",
                    ),
                ),
                (
                    "sales_manager",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="managed_opportunities",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="负责销售",
                    ),
                ),
                (
                    "team_members",
                    models.ManyToManyField(
                        blank=True,
                        related_name="participated_opportunities",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="参与团队成员",
                    ),
                ),
            ],
            options={
                "verbose_name": "商机",
                "verbose_name_plural": "商机列表",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        choices=[
                            ("SALES", "销售部"),
                            ("PRE_SALES", "售前部"),
                            ("POC", "POC测试部"),
                            ("RND", "研发中心"),
                            ("LAB", "实验室"),
                            ("OTHER", "其他"),
                        ],
                        default="OTHER",
                        max_length=20,
                        verbose_name="所属部门",
                    ),
                ),
                (
                    "job_role",
                    models.CharField(
                        choices=[
                            ("SALES_REP", "销售经理"),
                            ("PRODUCT", "产品经理"),
                            ("TEST", "测试工程师"),
                            ("IMPL", "实施工程师"),
                            ("FRONTEND", "前端工程师"),
                            ("BACKEND", "后端工程师"),
                            ("UI", "UI设计师"),
                            ("LAB_XIAORANG", "霄壤实验室人员"),
                            ("LAB_GAMMA", "伽玛实验室人员"),
                            ("MEMBER", "普通成员"),
                            ("MANAGER", "部门经理"),
                        ],
                        default="MEMBER",
                        max_length=20,
                        verbose_name="具体角色/岗位",
                    ),
                ),
                (
                    "avatar",
                    models.URLField(blank=True, null=True, verbose_name="头像URL"),
                ),
                (
                    "wechat_openid",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="微信OpenID"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="关联用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户档案",
                "verbose_name_plural": "用户档案",
            },
        ),
        migrations.CreateModel(
            name="OpportunityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=50, verbose_name="动作")),
                ("content", models.TextField(verbose_name="跟进内容/备注")),
                (
                    "stage_snapshot",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="当时阶段"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="记录时间"),
                ),
                (
                    "operator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="操作人",
                    ),
                ),
                (
                    "opportunity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="core.opportunity",
                        verbose_name="关联商机",
                    ),
                ),
            ],
            options={
                "verbose_name": "跟进记录",
                "verbose_name_plural": "跟进记录",
            },
        ),
    ]
