# Generated by Django 4.2.27 on 2025-12-05 04:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="job_role",
            field=models.CharField(
                choices=[
                    ("SALES_REP", "销售经理"),
                    ("PRE_SALES", "售前工程师"),
                    ("POC", "POC测试工程师"),
                    ("PRODUCT", "产品经理"),
                    ("TEST", "测试工程师"),
                    ("IMPL", "实施工程师"),
                    ("FRONTEND", "前端工程师"),
                    ("BACKEND", "后端工程师"),
                    ("UI", "UI设计师"),
                    ("LAB_XIAORANG", "霄壤实验室人员"),
                    ("LAB_GAMMA", "伽玛实验室人员"),
                    ("MEMBER", "普通成员"),
                    ("MANAGER", "部门经理"),
                ],
                default="MEMBER",
                max_length=20,
                verbose_name="具体角色/岗位",
            ),
        ),
    ]
