# Generated by Django 4.2.27 on 2025-12-05 04:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0002_alter_userprofile_job_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="PerformanceTarget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField(default=2025, verbose_name="年份")),
                (
                    "quarter",
                    models.IntegerField(
                        choices=[
                            (1, "第一季度"),
                            (2, "第二季度"),
                            (3, "第三季度"),
                            (4, "第四季度"),
                            (0, "全年"),
                        ],
                        default=0,
                        verbose_name="季度 (0代表全年)",
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        choices=[
                            ("SALES", "销售部"),
                            ("PRE_SALES", "售前部"),
                            ("POC", "POC测试部"),
                            ("RND", "研发中心"),
                            ("LAB", "实验室"),
                            ("OTHER", "其他"),
                        ],
                        default="SALES",
                        max_length=20,
                        verbose_name="目标部门",
                    ),
                ),
                (
                    "target_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="签约金额目标",
                    ),
                ),
                (
                    "target_gross_profit",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=12, verbose_name="毛利目标"
                    ),
                ),
                (
                    "target_revenue",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=12, verbose_name="营收目标"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="目标个人 (留空则为部门目标)",
                    ),
                ),
            ],
            options={
                "verbose_name": "业绩目标",
                "verbose_name_plural": "业绩目标",
                "unique_together": {("year", "quarter", "department", "user")},
            },
        ),
    ]
