# Generated by Django 4.2.27 on 2025-12-05 09:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_performancetarget"),
    ]

    operations = [
        migrations.AlterField(
            model_name="performancetarget",
            name="department",
            field=models.CharField(
                choices=[
                    ("SALES", "销售部"),
                    ("PRE_SALES", "售前部"),
                    ("POC", "POC测试部"),
                    ("GAME", "春秋GAME"),
                    ("RND", "研发中心"),
                    ("LAB", "标准实践实验室"),
                    ("OTHER", "其他"),
                ],
                default="SALES",
                max_length=20,
                verbose_name="目标部门",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="department",
            field=models.CharField(
                choices=[
                    ("SALES", "销售部"),
                    ("PRE_SALES", "售前部"),
                    ("POC", "POC测试部"),
                    ("GAME", "春秋GAME"),
                    ("RND", "研发中心"),
                    ("LAB", "标准实践实验室"),
                    ("OTHER", "其他"),
                ],
                default="OTHER",
                max_length=20,
                verbose_name="所属部门",
            ),
        ),
    ]
