# Generated by Django 4.2.27 on 2025-12-05 10:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0004_alter_performancetarget_department_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="opportunity",
            name="team_members",
            field=models.ManyToManyField(
                blank=True,
                related_name="participated_opportunities",
                to=settings.AUTH_USER_MODEL,
                verbose_name="参与团队成员(简易)",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="job_role",
            field=models.CharField(
                choices=[
                    ("SALES_REP", "销售经理"),
                    ("PRE_SALES", "售前工程师"),
                    ("POC", "POC测试工程师"),
                    ("GROUP_MARKETING", "集团市场部"),
                    ("PRODUCT", "产品经理"),
                    ("TEST", "测试工程师"),
                    ("IMPL", "实施工程师"),
                    ("FRONTEND", "前端工程师"),
                    ("BACKEND", "后端工程师"),
                    ("UI", "UI设计师"),
                    ("LAB_XIAORANG", "霄壤实验室人员"),
                    ("LAB_GAMMA", "伽玛实验室人员"),
                    ("MEMBER", "普通成员"),
                    ("MANAGER", "部门经理"),
                ],
                default="MEMBER",
                max_length=20,
                verbose_name="具体角色/岗位",
            ),
        ),
        migrations.CreateModel(
            name="OpportunityTeamMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(blank=True, max_length=50, verbose_name="姓名"),
                ),
                (
                    "department_name",
                    models.CharField(
                        blank=True,
                        help_text="如：集团市场部、其他部门",
                        max_length=50,
                        verbose_name="部门名称",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("SALES", "销售"),
                            ("PRE_SALES", "售前"),
                            ("POC", "POC/春秋GAME"),
                            ("RND", "研发"),
                            ("MARKETING", "集团市场部"),
                            ("OTHER", "其他"),
                        ],
                        default="OTHER",
                        max_length=50,
                        verbose_name="角色",
                    ),
                ),
                ("responsibility", models.TextField(blank=True, verbose_name="责任分工")),
                (
                    "workload",
                    models.DecimalField(
                        decimal_places=1,
                        default=0,
                        max_digits=5,
                        verbose_name="投入工时(人天)",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(blank=True, null=True, verbose_name="进入时间"),
                ),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="退出时间"),
                ),
                (
                    "opportunity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="core.opportunity",
                        verbose_name="关联商机",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="内部系统用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "项目组成员",
                "verbose_name_plural": "项目组成员",
            },
        ),
    ]
