# Generated by Django 4.2.27 on 2025-12-05 10:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_alter_opportunity_team_members_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="opportunityteammember",
            name="role",
            field=models.CharField(
                choices=[
                    ("SALES", "销售"),
                    ("PRE_SALES", "售前"),
                    ("GAME", "春秋GAME"),
                    ("RND", "研发"),
                    ("MARKETING", "集团市场部"),
                    ("OTHER", "其他"),
                ],
                default="OTHER",
                max_length=50,
                verbose_name="角色",
            ),
        ),
        migrations.AlterField(
            model_name="performancetarget",
            name="department",
            field=models.CharField(
                choices=[
                    ("SALES", "销售部"),
                    ("GAME", "春秋GAME"),
                    ("GROUP_MARKETING", "集团市场部"),
                    ("LAB", "标准实践实验室"),
                    ("RND", "研发中心"),
                    ("OTHER", "其他"),
                ],
                default="SALES",
                max_length=20,
                verbose_name="目标部门",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="department",
            field=models.CharField(
                choices=[
                    ("SALES", "销售部"),
                    ("GAME", "春秋GAME"),
                    ("GROUP_MARKETING", "集团市场部"),
                    ("LAB", "标准实践实验室"),
                    ("RND", "研发中心"),
                    ("OTHER", "其他"),
                ],
                default="OTHER",
                max_length=20,
                verbose_name="所属部门",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="job_role",
            field=models.CharField(
                choices=[
                    ("SALES_REP", "销售经理"),
                    ("PRE_SALES", "售前工程师"),
                    ("MARKETING", "市场专员"),
                    ("GAME_ENG", "春秋GAME工程师"),
                    ("PRODUCT", "产品经理"),
                    ("DEV_LEADER", "研发负责人"),
                    ("FRONTEND", "前端工程师"),
                    ("BACKEND", "后端工程师"),
                    ("TEST", "测试工程师"),
                    ("UI", "UI设计师"),
                    ("IMPL", "实施工程师"),
                    ("LAB_RES", "实验室研究员"),
                    ("MEMBER", "普通成员"),
                    ("MANAGER", "部门经理"),
                ],
                default="MEMBER",
                max_length=20,
                verbose_name="具体角色/岗位",
            ),
        ),
    ]
