# Generated by Django 4.2.27 on 2025-12-05 10:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0006_alter_opportunityteammember_role_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="opportunityteammember",
            name="department_name",
        ),
        migrations.AddField(
            model_name="opportunityteammember",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="添加时间"
            ),
        ),
        migrations.AlterField(
            model_name="opportunity",
            name="team_members",
            field=models.ManyToManyField(
                blank=True,
                related_name="participated_opportunities",
                to=settings.AUTH_USER_MODEL,
                verbose_name="参与团队成员(简单)",
            ),
        ),
        migrations.AlterField(
            model_name="opportunityteammember",
            name="end_date",
            field=models.DateField(blank=True, null=True, verbose_name="离开项目时间"),
        ),
        migrations.AlterField(
            model_name="opportunityteammember",
            name="name",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="成员姓名(如非系统用户)"
            ),
        ),
        migrations.AlterField(
            model_name="opportunityteammember",
            name="opportunity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="detailed_members",
                to="core.opportunity",
                verbose_name="关联商机",
            ),
        ),
        migrations.AlterField(
            model_name="opportunityteammember",
            name="role",
            field=models.CharField(
                choices=[
                    ("SALES_REP", "销售经理"),
                    ("PRE_SALES", "售前工程师"),
                    ("GAME_ENGINEER", "春秋GAME工程师"),
                    ("MARKETING_RND", "市场部研发人员"),
                    ("PRODUCT", "产品经理"),
                    ("TEST", "测试工程师"),
                    ("IMPL", "实施工程师"),
                    ("FRONTEND", "前端工程师"),
                    ("BACKEND", "后端工程师"),
                    ("UI", "UI设计师"),
                    ("LAB_XIAORANG", "霄壤实验室人员"),
                    ("LAB_GAMMA", "伽玛实验室人员"),
                    ("MEMBER", "普通成员"),
                    ("MANAGER", "部门经理"),
                    ("OTHER", "其他人员"),
                ],
                default="MEMBER",
                max_length=20,
                verbose_name="项目中角色",
            ),
        ),
        migrations.AlterField(
            model_name="opportunityteammember",
            name="start_date",
            field=models.DateField(blank=True, null=True, verbose_name="进入项目时间"),
        ),
        migrations.AlterField(
            model_name="opportunityteammember",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="系统用户",
            ),
        ),
        migrations.AlterField(
            model_name="opportunityteammember",
            name="workload",
            field=models.DecimalField(
                decimal_places=1, default=0.0, max_digits=6, verbose_name="投入工时(人天)"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="job_role",
            field=models.CharField(
                choices=[
                    ("SALES_REP", "销售经理"),
                    ("PRE_SALES", "售前工程师"),
                    ("GAME_ENGINEER", "春秋GAME工程师"),
                    ("MARKETING_RND", "市场部研发人员"),
                    ("PRODUCT", "产品经理"),
                    ("TEST", "测试工程师"),
                    ("IMPL", "实施工程师"),
                    ("FRONTEND", "前端工程师"),
                    ("BACKEND", "后端工程师"),
                    ("UI", "UI设计师"),
                    ("LAB_XIAORANG", "霄壤实验室人员"),
                    ("LAB_GAMMA", "伽玛实验室人员"),
                    ("MEMBER", "普通成员"),
                    ("MANAGER", "部门经理"),
                    ("OTHER", "其他人员"),
                ],
                default="MEMBER",
                max_length=20,
                verbose_name="具体角色/岗位",
            ),
        ),
    ]
