# Generated by Django 4.2.27 on 2025-12-05 14:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_remove_opportunityteammember_department_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="opportunity",
            name="amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="项目预计签约的总金额（商机池金额）",
                max_digits=12,
                verbose_name="预计金额",
            ),
        ),
        migrations.AlterField(
            model_name="opportunity",
            name="gross_profit",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="扣除成本后的实际回款毛利",
                max_digits=12,
                verbose_name="回款毛利",
            ),
        ),
        migrations.AlterField(
            model_name="opportunity",
            name="revenue",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="财务确认的收入金额",
                max_digits=12,
                verbose_name="确认收入金额",
            ),
        ),
        migrations.AlterField(
            model_name="opportunity",
            name="signed_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="实际签订合同的金额",
                max_digits=12,
                verbose_name="新签合同金额",
            ),
        ),
        migrations.AlterField(
            model_name="opportunity",
            name="stage",
            field=models.CharField(
                choices=[
                    ("CONTACT", "接触阶段"),
                    ("REQ_ANALYSIS", "需求分析"),
                    ("INITIATION", "客户立项"),
                    ("BIDDING", "招采阶段"),
                    ("DELIVERY", "交付实施"),
                    ("AFTER_SALES", "售后阶段"),
                    ("COMPLETED", "项目完成"),
                ],
                default="CONTACT",
                max_length=20,
                verbose_name="当前阶段",
            ),
        ),
        migrations.AlterField(
            model_name="opportunity",
            name="status",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "进行中"),
                    ("WON", "赢单"),
                    ("LOST", "输单"),
                    ("SUSPENDED", "挂起"),
                    ("COMPLETED", "已完成"),
                ],
                default="ACTIVE",
                max_length=20,
                verbose_name="商机状态",
            ),
        ),
        migrations.AlterField(
            model_name="performancetarget",
            name="target_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="对应新签合同金额",
                max_digits=12,
                verbose_name="签约金额目标",
            ),
        ),
        migrations.AlterField(
            model_name="performancetarget",
            name="target_gross_profit",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="对应回款毛利",
                max_digits=12,
                verbose_name="毛利目标",
            ),
        ),
        migrations.AlterField(
            model_name="performancetarget",
            name="target_revenue",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="对应确认收入金额",
                max_digits=12,
                verbose_name="营收目标",
            ),
        ),
    ]
