# Generated by Django 4.2.27 on 2025-12-05 15:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_alter_opportunity_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="opportunity",
            name="profit",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="合同金额 - 预计成本",
                max_digits=12,
                verbose_name="毛利",
            ),
        ),
        migrations.AddField(
            model_name="performancetarget",
            name="target_profit",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="对应合同毛利",
                max_digits=12,
                verbose_name="毛利目标",
            ),
        ),
        migrations.AlterField(
            model_name="performancetarget",
            name="target_gross_profit",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="对应回款毛利",
                max_digits=12,
                verbose_name="回款毛利目标",
            ),
        ),
    ]
