# Generated by Django 4.2.27 on 2025-12-05 15:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_opportunity_profit_performancetarget_target_profit_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="performancetarget",
            name="target_profit",
        ),
        migrations.AlterField(
            model_name="performancetarget",
            name="target_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="对应新签合同金额",
                max_digits=12,
                verbose_name="新签合同金额目标",
            ),
        ),
        migrations.AlterField(
            model_name="performancetarget",
            name="target_revenue",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="对应确认收入金额",
                max_digits=12,
                verbose_name="确认收入目标",
            ),
        ),
    ]
