# Generated by Django 4.2.27 on 2025-12-05 16:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0010_remove_performancetarget_target_profit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='customer_company',
            field=models.CharField(max_length=200, verbose_name='客户公司(文本)'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='customer_name',
            field=models.CharField(max_length=100, verbose_name='客户姓名(文本)'),
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='客户名称')),
                ('industry', models.CharField(blank=True, max_length=100, verbose_name='所属行业')),
                ('scale', models.CharField(blank=True, choices=[('SMALL', '小微企业 (<50人)'), ('MEDIUM', '中型企业 (50-500人)'), ('LARGE', '大型企业 (500-2000人)'), ('ENTERPRISE', '集团/超大型 (>2000人)'), ('GOV', '政府机构/事业单位')], max_length=20, verbose_name='规模')),
                ('status', models.CharField(choices=[('POTENTIAL', '潜在客户'), ('ACTIVE', '活跃客户'), ('KEY', '重点客户'), ('CHURNED', '流失客户')], default='POTENTIAL', max_length=20, verbose_name='客户状态')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='办公地址')),
                ('website', models.URLField(blank=True, verbose_name='官网')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_customers', to=settings.AUTH_USER_MODEL, verbose_name='负责销售')),
            ],
            options={
                'verbose_name': '客户管理',
                'verbose_name_plural': '客户管理',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='职位/头衔')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='联系电话')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='邮箱')),
                ('wechat', models.CharField(blank=True, max_length=100, verbose_name='微信号')),
                ('department', models.CharField(blank=True, max_length=100, verbose_name='所在部门')),
                ('is_decision_maker', models.BooleanField(default=False, verbose_name='是否关键决策人')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='core.customer', verbose_name='所属客户')),
            ],
            options={
                'verbose_name': '联系人',
                'verbose_name_plural': '联系人',
            },
        ),
        migrations.AddField(
            model_name='opportunity',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='opportunities', to='core.customer', verbose_name='关联客户'),
        ),
    ]
