# Generated by Django 4.2.27 on 2025-12-05 16:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0011_alter_opportunity_customer_company_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="ai_raw_text",
            field=models.TextField(blank=True, verbose_name="原始信息(AI解析)"),
        ),
        migrations.AddField(
            model_name="contact",
            name="reports_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="subordinates",
                to="core.contact",
                verbose_name="汇报给",
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="ai_raw_text",
            field=models.TextField(
                blank=True, help_text="在此粘贴大段客户介绍，后续通过AI自动提取", verbose_name="原始信息(AI解析)"
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="legal_representative",
            field=models.CharField(blank=True, max_length=100, verbose_name="法人代表"),
        ),
        migrations.AddField(
            model_name="customer",
            name="registered_capital",
            field=models.CharField(blank=True, max_length=100, verbose_name="注册资金"),
        ),
        migrations.AddField(
            model_name="opportunity",
            name="ai_raw_text",
            field=models.TextField(
                blank=True, help_text="在此粘贴大段商机介绍，后续通过AI自动提取", verbose_name="原始信息(AI解析)"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="reports_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="subordinates",
                to="core.userprofile",
                verbose_name="汇报给",
            ),
        ),
        migrations.CreateModel(
            name="MarketActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="活动名称")),
                ("time", models.DateField(verbose_name="活动时间")),
                ("location", models.CharField(max_length=200, verbose_name="活动地点")),
                (
                    "type",
                    models.CharField(
                        help_text="如：展会, 沙龙, 峰会等", max_length=100, verbose_name="活动类型"
                    ),
                ),
                (
                    "scale",
                    models.CharField(blank=True, max_length=100, verbose_name="规模"),
                ),
                ("description", models.TextField(blank=True, verbose_name="活动详情")),
                (
                    "ai_raw_text",
                    models.TextField(blank=True, verbose_name="原始信息(AI解析)"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "confirmed_by",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"profile__department": "GROUP_MARKETING"},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="confirmed_activities",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="确认人(集团市场部)",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_activities",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="录入人",
                    ),
                ),
            ],
            options={
                "verbose_name": "市场活动",
                "verbose_name_plural": "市场活动",
            },
        ),
        migrations.CreateModel(
            name="Competition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="赛事名称")),
                ("time", models.DateField(verbose_name="赛事时间")),
                ("location", models.CharField(max_length=200, verbose_name="举办地点")),
                (
                    "format",
                    models.CharField(
                        choices=[
                            ("ONLINE", "线上"),
                            ("OFFLINE", "线下"),
                            ("HYBRID", "线上+线下"),
                        ],
                        default="OFFLINE",
                        max_length=20,
                        verbose_name="举办形式",
                    ),
                ),
                (
                    "system_format",
                    models.CharField(
                        blank=True,
                        help_text="如：CTF, AWD, 攻防演练等",
                        max_length=100,
                        verbose_name="赛制",
                    ),
                ),
                (
                    "scale",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="参赛人数/规模"
                    ),
                ),
                (
                    "target_audience",
                    models.CharField(blank=True, max_length=200, verbose_name="参赛群体"),
                ),
                (
                    "industry",
                    models.CharField(blank=True, max_length=100, verbose_name="所属行业"),
                ),
                (
                    "level",
                    models.CharField(blank=True, max_length=50, verbose_name="赛事级别"),
                ),
                ("description", models.TextField(blank=True, verbose_name="赛事详情")),
                (
                    "ai_raw_text",
                    models.TextField(blank=True, verbose_name="原始信息(AI解析)"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "confirmed_by",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"profile__department": "GAME"},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="confirmed_competitions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="确认人(春秋GAME)",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_competitions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="录入人",
                    ),
                ),
            ],
            options={
                "verbose_name": "赛事管理",
                "verbose_name_plural": "赛事管理",
            },
        ),
    ]
