# Generated by Django 4.2.27 on 2025-12-05 17:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0012_contact_ai_raw_text_contact_reports_to_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMediaStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(help_text='如：永信至诚公众号, 勒索病毒头条, i春秋, 春秋伽玛', max_length=100, verbose_name='平台/账号名称')),
                ('fans_count', models.IntegerField(default=0, verbose_name='粉丝数')),
                ('record_date', models.DateField(auto_now_add=True, verbose_name='记录日期')),
            ],
            options={
                'verbose_name': '粉丝数据统计',
                'verbose_name_plural': '粉丝数据统计',
            },
        ),
        migrations.AddField(
            model_name='competition',
            name='status',
            field=models.CharField(choices=[('DRAFT', '草稿'), ('PENDING', '待确认/审核中'), ('APPROVED', '已确认/已发布'), ('REJECTED', '已驳回')], default='DRAFT', max_length=20, verbose_name='审批状态'),
        ),
        migrations.AddField(
            model_name='marketactivity',
            name='status',
            field=models.CharField(choices=[('DRAFT', '草稿'), ('PENDING', '待确认/审核中'), ('APPROVED', '已确认/已发布'), ('REJECTED', '已驳回')], default='DRAFT', max_length=20, verbose_name='审批状态'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='approval_status',
            field=models.CharField(choices=[('DRAFT', '草稿'), ('PENDING', '待确认/审核中'), ('APPROVED', '已确认/已发布'), ('REJECTED', '已驳回')], default='DRAFT', max_length=20, verbose_name='审批状态'),
        ),
        migrations.CreateModel(
            name='WorkReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('DAILY', '日报'), ('WEEKLY', '周报'), ('MONTHLY', '月报')], default='DAILY', max_length=20, verbose_name='报告类型')),
                ('report_date', models.DateField(verbose_name='汇报日期')),
                ('content', models.TextField(verbose_name='工作内容')),
                ('ai_summary', models.TextField(blank=True, verbose_name='AI总结')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('related_opportunities', models.ManyToManyField(blank=True, to='core.opportunity', verbose_name='关联商机')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_reports', to=settings.AUTH_USER_MODEL, verbose_name='汇报人')),
            ],
            options={
                'verbose_name': '工作日报/周报',
                'verbose_name_plural': '工作日报/周报',
            },
        ),
        migrations.CreateModel(
            name='TodoTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='任务标题')),
                ('description', models.TextField(blank=True, verbose_name='任务描述')),
                ('object_id', models.PositiveIntegerField()),
                ('is_completed', models.BooleanField(default=False, verbose_name='是否完成')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todo_tasks', to=settings.AUTH_USER_MODEL, verbose_name='负责人')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': '待办任务',
                'verbose_name_plural': '待办任务',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='公告标题')),
                ('content', models.TextField(verbose_name='公告内容')),
                ('type', models.CharField(choices=[('SYSTEM', '系统公告'), ('DEPARTMENT', '部门公告')], default='DEPARTMENT', max_length=20, verbose_name='公告类型')),
                ('department', models.CharField(blank=True, choices=[('SALES', '销售部'), ('GAME', '春秋GAME'), ('GROUP_MARKETING', '集团市场部'), ('LAB', '标准实践实验室'), ('RND', '研发中心'), ('OTHER', '其他')], max_length=20, null=True, verbose_name='所属部门')),
                ('status', models.CharField(choices=[('DRAFT', '草稿'), ('PENDING', '待确认/审核中'), ('APPROVED', '已确认/已发布'), ('REJECTED', '已驳回')], default='DRAFT', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='发布时间')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_announcements', to=settings.AUTH_USER_MODEL, verbose_name='发布人')),
            ],
            options={
                'verbose_name': '公告',
                'verbose_name_plural': '公告',
            },
        ),
    ]
