# Generated by Django 4.2.27 on 2025-12-05 17:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0013_socialmediastats_competition_status_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="announcement",
            name="department",
        ),
        migrations.AddField(
            model_name="announcement",
            name="target_departments",
            field=models.JSONField(
                blank=True, default=list, help_text="选择接收公告的部门", verbose_name="目标部门"
            ),
        ),
    ]
