# Generated by Django 4.2.27 on 2025-12-05 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("core", "0014_remove_announcement_department_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="todotask",
            name="deadline",
            field=models.DateTimeField(blank=True, null=True, verbose_name="截止时间"),
        ),
        migrations.AddField(
            model_name="todotask",
            name="source_type",
            field=models.CharField(
                choices=[
                    ("WORKFLOW", "流程审核"),
                    ("MANUAL_SELF", "个人自建"),
                    ("MANUAL_ASSIGN", "上级指派"),
                    ("AI_GENERATED", "AI智能解析"),
                ],
                default="MANUAL_SELF",
                max_length=20,
                verbose_name="任务来源",
            ),
        ),
        migrations.AlterField(
            model_name="todotask",
            name="content_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AlterField(
            model_name="todotask",
            name="object_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
