# Generated by Django 4.2.27 on 2025-12-05 18:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0015_todotask_deadline_todotask_source_type_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="competition",
            options={"verbose_name": "赛事信息", "verbose_name_plural": "赛事信息"},
        ),
        migrations.AlterModelOptions(
            name="workreport",
            options={"verbose_name": "工作报告", "verbose_name_plural": "工作报告"},
        ),
        migrations.AddField(
            model_name="workreport",
            name="ai_raw_input",
            field=models.TextField(
                blank=True,
                help_text="在此输入一句话总结，AI将自动生成详细报告内容。例如：“今天完成了商机A的拜访，和张总确认了需求，明天计划写方案”",
                verbose_name="AI原始指令",
            ),
        ),
        migrations.AlterField(
            model_name="workreport",
            name="content",
            field=models.TextField(blank=True, verbose_name="工作内容"),
        ),
    ]
