# Generated by Django 4.2.27 on 2025-12-05 19:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0016_alter_competition_options_alter_workreport_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="department",
            field=models.CharField(
                choices=[
                    ("SALES", "销售部"),
                    ("GAME", "春秋GAME"),
                    ("GROUP_MARKETING", "集团市场部"),
                    ("LAB", "标准实践实验室"),
                    ("RND", "研发中心"),
                    ("OTHER", "其他"),
                ],
                default="OTHER",
                max_length=20,
                verbose_name="所属部门(旧)",
            ),
        ),
        migrations.CreateModel(
            name="DepartmentModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="部门名称")),
                ("description", models.TextField(blank=True, verbose_name="部门职责/描述")),
                ("order", models.IntegerField(default=0, verbose_name="显示顺序")),
                (
                    "manager",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="managed_departments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="部门负责人",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="core.departmentmodel",
                        verbose_name="上级部门",
                    ),
                ),
            ],
            options={
                "verbose_name": "组织架构",
                "verbose_name_plural": "组织架构",
                "ordering": ["order", "name"],
            },
        ),
        migrations.AddField(
            model_name="userprofile",
            name="department_link",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="members",
                to="core.departmentmodel",
                verbose_name="所属部门(新)",
            ),
        ),
    ]
