# Generated by Django 4.2.27 on 2025-12-05 19:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0017_alter_userprofile_department_departmentmodel_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="departmentmodel",
            name="category",
            field=models.CharField(
                choices=[
                    ("SALES", "销售部门"),
                    ("RND", "研发产线"),
                    ("POC", "POC/技术支持"),
                    ("LAB", "实验室"),
                    ("FUNCTIONAL", "职能部门"),
                    ("OTHER", "其他"),
                ],
                default="OTHER",
                max_length=20,
                verbose_name="部门性质",
            ),
        ),
    ]
