# Generated by Django 4.2.27 on 2025-12-05 19:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0018_departmentmodel_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="competition",
            name="challenge_count",
            field=models.CharField(blank=True, max_length=50, verbose_name="题目数量"),
        ),
        migrations.AddField(
            model_name="competition",
            name="challenge_type",
            field=models.CharField(blank=True, max_length=100, verbose_name="题目类型"),
        ),
        migrations.AddField(
            model_name="competition",
            name="contact_person",
            field=models.CharField(blank=True, max_length=50, verbose_name="对接人"),
        ),
        migrations.AddField(
            model_name="competition",
            name="department_name",
            field=models.CharField(blank=True, max_length=100, verbose_name="部门"),
        ),
        migrations.AddField(
            model_name="competition",
            name="duration",
            field=models.CharField(blank=True, max_length=50, verbose_name="比赛时长"),
        ),
        migrations.AddField(
            model_name="competition",
            name="end_time",
            field=models.DateField(blank=True, null=True, verbose_name="结束时间"),
        ),
        migrations.AddField(
            model_name="competition",
            name="host_type",
            field=models.CharField(blank=True, max_length=50, verbose_name="主办类型"),
        ),
        migrations.AddField(
            model_name="competition",
            name="impact_level",
            field=models.CharField(blank=True, max_length=50, verbose_name="赛事/影响力热度"),
        ),
        migrations.AddField(
            model_name="competition",
            name="leader_count",
            field=models.CharField(blank=True, max_length=50, verbose_name="领队人数"),
        ),
        migrations.AddField(
            model_name="competition",
            name="organizers",
            field=models.TextField(blank=True, verbose_name="组织机构"),
        ),
        migrations.AddField(
            model_name="competition",
            name="owner_name",
            field=models.CharField(blank=True, max_length=50, verbose_name="负责人"),
        ),
        migrations.AddField(
            model_name="competition",
            name="participant_count",
            field=models.CharField(blank=True, max_length=50, verbose_name="实际总人数"),
        ),
        migrations.AddField(
            model_name="competition",
            name="project_code",
            field=models.CharField(blank=True, max_length=100, verbose_name="项目编号"),
        ),
        migrations.AddField(
            model_name="competition",
            name="project_name",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="立项名称/实训项目名称"
            ),
        ),
        migrations.AddField(
            model_name="competition",
            name="team_count",
            field=models.CharField(blank=True, max_length=50, verbose_name="队伍数量"),
        ),
        migrations.AddField(
            model_name="competition",
            name="type",
            field=models.CharField(
                blank=True, help_text="比赛/实战/培训/集训/其他", max_length=50, verbose_name="类型"
            ),
        ),
        migrations.AlterField(
            model_name="competition",
            name="creator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_competitions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="录入人",
            ),
        ),
        migrations.AlterField(
            model_name="competition",
            name="description",
            field=models.TextField(blank=True, verbose_name="备注/赛事详情"),
        ),
        migrations.AlterField(
            model_name="competition",
            name="level",
            field=models.CharField(blank=True, max_length=50, verbose_name="级别"),
        ),
        migrations.AlterField(
            model_name="competition",
            name="location",
            field=models.CharField(blank=True, max_length=200, verbose_name="活动地点"),
        ),
        migrations.AlterField(
            model_name="competition",
            name="name",
            field=models.CharField(max_length=200, verbose_name="比赛名称"),
        ),
        migrations.AlterField(
            model_name="competition",
            name="scale",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="参赛人数/规模 (旧)"
            ),
        ),
        migrations.AlterField(
            model_name="competition",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "草稿"),
                    ("PENDING", "待确认/审核中"),
                    ("APPROVED", "已确认/已发布"),
                    ("REJECTED", "已驳回"),
                ],
                default="DRAFT",
                max_length=20,
                verbose_name="状态",
            ),
        ),
        migrations.AlterField(
            model_name="competition",
            name="target_audience",
            field=models.CharField(blank=True, max_length=200, verbose_name="面向对象"),
        ),
        migrations.AlterField(
            model_name="competition",
            name="time",
            field=models.DateField(blank=True, null=True, verbose_name="开始时间"),
        ),
    ]
