# Generated by Django 4.2.27 on 2025-12-05 20:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0019_competition_challenge_count_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AIConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="例如：DeepSeek生产环境", max_length=50, verbose_name="配置名称"
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("OPENAI", "OpenAI (及兼容接口)"),
                            ("DEEPSEEK", "DeepSeek"),
                            ("MOONSHOT", "Kimi (Moonshot)"),
                            ("ALIYUN", "通义千问"),
                            ("OTHER", "其他"),
                        ],
                        default="DEEPSEEK",
                        max_length=20,
                        verbose_name="服务提供商",
                    ),
                ),
                ("api_key", models.CharField(max_length=200, verbose_name="API Key")),
                (
                    "base_url",
                    models.CharField(
                        blank=True,
                        help_text="如果是OpenAI兼容接口，请填写Base URL，例如：https://api.deepseek.com/v1",
                        max_length=200,
                        verbose_name="API Base URL",
                    ),
                ),
                (
                    "model_name",
                    models.CharField(
                        default="deepseek-chat",
                        help_text="例如：gpt-3.5-turbo, deepseek-chat, moonshot-v1-8k",
                        max_length=100,
                        verbose_name="模型名称",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=False, help_text="系统中同一时间只能启用一个配置", verbose_name="是否启用"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "AI模型配置",
                "verbose_name_plural": "AI模型配置",
            },
        ),
    ]
