# Generated by Django 4.2.27 on 2025-12-06 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_aiconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiconfiguration',
            name='supports_vision',
            field=models.BooleanField(default=False, help_text='该模型是否支持图片识别功能', verbose_name='支持视觉/OCR'),
        ),
    ]
