# Generated by Django 4.2.27 on 2025-12-06 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_aiconfiguration_supports_vision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiconfiguration',
            name='provider',
            field=models.CharField(choices=[('OPENAI', 'OpenAI (及兼容接口)'), ('DEEPSEEK', 'DeepSeek'), ('OLLAMA', 'Ollama (Local)'), ('MOONSHOT', 'Kimi (Moonshot)'), ('ALIYUN', '通义千问'), ('OTHER', '其他')], default='DEEPSEEK', max_length=20, verbose_name='服务提供商'),
        ),
    ]
