# Generated by Django 4.2.27 on 2025-12-06 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_aiconfiguration_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiconfiguration',
            name='prompt_competition',
            field=models.TextField(blank=True, help_text='针对赛事信息解析的专用提示词', verbose_name='赛事信息提示词'),
        ),
        migrations.AddField(
            model_name='aiconfiguration',
            name='prompt_customer',
            field=models.TextField(blank=True, help_text='针对客户信息解析的专用提示词', verbose_name='客户录入提示词'),
        ),
        migrations.AddField(
            model_name='aiconfiguration',
            name='prompt_market_activity',
            field=models.TextField(blank=True, help_text='针对市场活动解析的专用提示词', verbose_name='市场活动提示词'),
        ),
        migrations.AddField(
            model_name='aiconfiguration',
            name='prompt_opportunity',
            field=models.TextField(blank=True, help_text='针对商机解析的专用提示词', verbose_name='商机录入提示词'),
        ),
        migrations.AddField(
            model_name='aiconfiguration',
            name='prompt_todo',
            field=models.TextField(blank=True, help_text='针对待办任务解析的专用提示词', verbose_name='待办事项提示词'),
        ),
        migrations.AddField(
            model_name='aiconfiguration',
            name='prompt_work_report',
            field=models.TextField(blank=True, help_text='针对工作报告生成的专用提示词', verbose_name='工作报告提示词'),
        ),
        migrations.AddField(
            model_name='aiconfiguration',
            name='system_prompt_global',
            field=models.TextField(blank=True, help_text='所有AI交互的默认系统提示词，用于设定AI的人设和语气', verbose_name='全局系统提示词'),
        ),
    ]
