# Generated by Django 4.2.27 on 2025-12-06 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_aiconfiguration_prompt_competition_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromptTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='例如：标准商机解析模板V1', max_length=100, verbose_name='模板名称')),
                ('scene', models.CharField(choices=[('GLOBAL', '全局系统提示词 (System)'), ('OPPORTUNITY', '商机录入'), ('CUSTOMER', '客户录入'), ('COMPETITION', '赛事信息'), ('MARKET', '市场活动'), ('TODO', '待办任务'), ('REPORT', '工作报告'), ('OTHER', '其他')], default='GLOBAL', max_length=50, verbose_name='应用场景')),
                ('template', models.TextField(help_text='在此编写详细的提示词指令', verbose_name='提示词内容')),
                ('is_active', models.BooleanField(default=True, help_text='同一场景建议只启用一个，系统将使用最新启用的模板', verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '提示词模板',
                'verbose_name_plural': '提示词模板',
                'ordering': ['scene', '-updated_at'],
            },
        ),
    ]
