# Generated by Django 4.2.27 on 2025-12-06 15:06

from django.db import migrations

def migrate_prompts(apps, schema_editor):
    AIConfiguration = apps.get_model('core', 'AIConfiguration')
    PromptTemplate = apps.get_model('core', 'PromptTemplate')

    # Mapping from AIConfiguration field to (Scene, Name Suffix)
    mapping = {
        'system_prompt_global': ('GLOBAL', '全局系统提示词'),
        'prompt_opportunity': ('OPPORTUNITY', '商机录入默认提示词'),
        'prompt_customer': ('CUSTOMER', '客户录入默认提示词'),
        'prompt_competition': ('COMPETITION', '赛事信息默认提示词'),
        'prompt_market_activity': ('MARKET', '市场活动默认提示词'),
        'prompt_todo': ('TODO', '待办任务默认提示词'),
        'prompt_work_report': ('REPORT', '工作报告默认提示词'),
    }

    for config in AIConfiguration.objects.all():
        for field, (scene, name_suffix) in mapping.items():
            content = getattr(config, field, '').strip()
            if content:
                PromptTemplate.objects.create(
                    name=f"{config.name} - {name_suffix}",
                    scene=scene,
                    template=content,
                    is_active=True # Make them active by default
                )

def reverse_migrate_prompts(apps, schema_editor):
    PromptTemplate = apps.get_model('core', 'PromptTemplate')
    PromptTemplate.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_prompttemplate'),
    ]

    operations = [
        migrations.RunPython(migrate_prompts, reverse_migrate_prompts),
    ]
