# Generated by Django 4.2.27 on 2025-12-06 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_migrate_prompts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aiconfiguration',
            name='prompt_competition',
        ),
        migrations.RemoveField(
            model_name='aiconfiguration',
            name='prompt_customer',
        ),
        migrations.RemoveField(
            model_name='aiconfiguration',
            name='prompt_market_activity',
        ),
        migrations.RemoveField(
            model_name='aiconfiguration',
            name='prompt_opportunity',
        ),
        migrations.RemoveField(
            model_name='aiconfiguration',
            name='prompt_todo',
        ),
        migrations.RemoveField(
            model_name='aiconfiguration',
            name='prompt_work_report',
        ),
        migrations.RemoveField(
            model_name='aiconfiguration',
            name='system_prompt_global',
        ),
    ]
