# Generated by Django 4.2.27 on 2025-12-06 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_remove_aiconfiguration_prompt_competition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiconfiguration',
            name='is_active',
            field=models.BooleanField(default=False, help_text='勾选此项，则在未选择模型时默认使用此配置', verbose_name='设为默认'),
        ),
    ]
