# Generated by Django 4.2.27 on 2025-12-08 08:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0027_alter_aiconfiguration_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='department',
            field=models.CharField(choices=[('SALES', '销售部'), ('GAME', '春秋GAME'), ('GROUP_MARKETING', '集团市场部'), ('LAB', '标准实践实验室'), ('RND', '研发中心'), ('OTHER', '其他')], default='OTHER', editable=False, max_length=20, verbose_name='所属部门(旧)'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='department_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='core.departmentmodel', verbose_name='所属部门'),
        ),
        migrations.CreateModel(
            name='OpportunityTransferApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(verbose_name='移交原因')),
                ('status', models.CharField(choices=[('DRAFT', '草稿'), ('PENDING', '待确认/审核中'), ('APPROVED', '已确认/已发布'), ('REJECTED', '已驳回')], default='PENDING', max_length=20, verbose_name='审批状态')),
                ('approval_note', models.TextField(blank=True, verbose_name='审批意见')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='申请时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applied_transfers', to=settings.AUTH_USER_MODEL, verbose_name='申请人')),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_transfers', to=settings.AUTH_USER_MODEL, verbose_name='审批人')),
                ('current_owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_from', to=settings.AUTH_USER_MODEL, verbose_name='当前负责人')),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_applications', to='core.opportunity', verbose_name='关联商机')),
                ('target_owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_to', to=settings.AUTH_USER_MODEL, verbose_name='目标负责人')),
            ],
            options={
                'verbose_name': '商机移交申请',
                'verbose_name_plural': '商机移交申请',
            },
        ),
    ]
