# Generated by Django 4.2.27 on 2025-12-08 10:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0028_alter_userprofile_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunitylog',
            name='transfer_target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_logs', to=settings.AUTH_USER_MODEL, verbose_name='移交给谁'),
        ),
    ]
