# Generated by Django 4.2.27 on 2025-12-08 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_opportunitylog_transfer_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='competitors',
            field=models.CharField(blank=True, help_text='多个对手用逗号分隔', max_length=255, verbose_name='竞争对手'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='description',
            field=models.TextField(blank=True, help_text='商机背景、需求详情等', verbose_name='商机描述/备注'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='source',
            field=models.CharField(blank=True, help_text='如：老客户推荐, 市场活动, 招标公告等', max_length=100, verbose_name='商机来源'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='win_rate',
            field=models.IntegerField(default=0, help_text='0-100之间', verbose_name='赢单概率(%)'),
        ),
    ]
