# Generated by Django 4.2.27 on 2025-12-08 17:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0030_opportunity_competitors_opportunity_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='customer_contact_name',
            field=models.CharField(blank=True, help_text='关键联系人姓名', max_length=100, verbose_name='客户联系人'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='customer_industry',
            field=models.CharField(blank=True, help_text='例如：教育, 金融, 能源, 政府等', max_length=100, verbose_name='客户行业'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='customer_region',
            field=models.CharField(blank=True, help_text='例如：华北区, 北京, 广东等', max_length=100, verbose_name='客户区域'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='product_line',
            field=models.CharField(blank=True, help_text='例如：网络靶场, 城市安全, 培训服务等', max_length=100, verbose_name='所属产线'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='project_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_projects', to=settings.AUTH_USER_MODEL, verbose_name='项目经理'),
        ),
    ]
