# Generated by Django 4.2.27 on 2025-12-08 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_opportunity_customer_contact_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='customer_email',
            field=models.CharField(blank=True, max_length=100, verbose_name='邮箱'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='customer_phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='联系电话'),
        ),
    ]
