# Generated by Django 4.2.27 on 2025-12-08 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_opportunity_customer_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_code',
            field=models.CharField(blank=True, help_text='例如：CUST-001', max_length=50, verbose_name='客户代号'),
        ),
    ]
