# Generated by Django 4.2.27 on 2025-12-10 15:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0034_customer_customer_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('OPPORTUNITY', '商机'), ('CUSTOMER', '客户'), ('CONTACT', '联系人'), ('ACTIVITY', '活动'), ('COMPETITION', '赛事')], max_length=20)),
                ('action', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': '统一动态',
                'verbose_name_plural': '统一动态',
                'ordering': ['-created_at'],
            },
        ),
    ]
