# Generated by Django 4.2.27 on 2025-12-10 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_activitylog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunityteammember',
            name='role',
            field=models.CharField(choices=[('SALES_REP', '销售经理'), ('PRE_SALES', '售前工程师'), ('GAME_ENGINEER', '春秋GAME工程师'), ('MARKETING_RND', '市场部研发人员'), ('PRODUCT', '产品经理'), ('TEST', '测试工程师'), ('IMPL', '实施工程师'), ('FRONTEND', '前端工程师'), ('BACKEND', '后端工程师'), ('UI', 'UI设计师'), ('LAB_XIAORANG', '霄壤实验室人员'), ('LAB_GAMMA', '伽玛实验室人员'), ('MEMBER', '普通成员'), ('MANAGER', '部门经理'), ('DIRECTOR', '总监'), ('VICE_DIRECTOR', '副总监'), ('OTHER', '其他人员')], default='MEMBER', max_length=20, verbose_name='项目中角色'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='job_role',
            field=models.CharField(choices=[('SALES_REP', '销售经理'), ('PRE_SALES', '售前工程师'), ('GAME_ENGINEER', '春秋GAME工程师'), ('MARKETING_RND', '市场部研发人员'), ('PRODUCT', '产品经理'), ('TEST', '测试工程师'), ('IMPL', '实施工程师'), ('FRONTEND', '前端工程师'), ('BACKEND', '后端工程师'), ('UI', 'UI设计师'), ('LAB_XIAORANG', '霄壤实验室人员'), ('LAB_GAMMA', '伽玛实验室人员'), ('MEMBER', '普通成员'), ('MANAGER', '部门经理'), ('DIRECTOR', '总监'), ('VICE_DIRECTOR', '副总监'), ('OTHER', '其他人员')], default='MEMBER', max_length=20, verbose_name='具体角色/岗位'),
        ),
    ]
