# Generated by Django 4.2.27 on 2025-12-10 15:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0037_approvalrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmediastats',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='创建时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='socialmediastats',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_social_stats', to=settings.AUTH_USER_MODEL, verbose_name='维护人'),
        ),
        migrations.AddField(
            model_name='socialmediastats',
            name='status',
            field=models.CharField(choices=[('DRAFT', '草稿'), ('PENDING', '待确认/审核中'), ('APPROVED', '已确认/已发布'), ('REJECTED', '已驳回')], default='PENDING', max_length=20, verbose_name='状态'),
        ),
        migrations.AddField(
            model_name='socialmediastats',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='socialmediastats',
            name='platform',
            field=models.CharField(max_length=100, verbose_name='平台/账号名称'),
        ),
    ]
