# Generated by Django 4.2.27 on 2025-12-10 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_socialmediastats_created_at_socialmediastats_creator_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='job_role',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='job_level',
            field=models.CharField(choices=[('M_GM', '总经理'), ('M_VGM', '副总经理'), ('M_DIRECTOR', '总监'), ('M_VDIRECTOR', '副总监'), ('M_SENIOR_MANAGER', '高级经理'), ('M_MANAGER', '经理'), ('P_ASSISTANT', '助理'), ('P_SPECIALIST', '专员'), ('P_SENIOR_SPECIALIST', '高级专员'), ('P_MANAGER', '经理'), ('P_SENIOR_MANAGER', '高级经理'), ('P_VDIRECTOR', '副总监'), ('P_DIRECTOR', '总监'), ('P_SENIOR_DIRECTOR', '高级总监'), ('P_SCIENTIST', '科学家'), ('S_INTERN', '实习生'), ('S_AE', '客户主任'), ('S_SAE', '高级客户主任'), ('S_AM', '客户经理'), ('S_SAM', '高级客户经理'), ('S_AD', '客户总监'), ('S_SAD', '高级客户总监')], default='P_SPECIALIST', max_length=30, verbose_name='职级'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='job_position',
            field=models.CharField(blank=True, choices=[('PRODUCT_MANAGER', '产品经理'), ('FRONTEND', '前端'), ('BACKEND', '后端'), ('OPS', '运维'), ('UI', 'UI'), ('DESIGN', '设计'), ('COPYWRITER', '文案'), ('MEDIA', '媒介'), ('OPERATION', '运营'), ('RESEARCHER', '研究员')], max_length=30, null=True, verbose_name='岗位'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='job_series',
            field=models.CharField(choices=[('M', '管理序列'), ('P', '技术序列'), ('S', '销售序列')], default='P', max_length=2, verbose_name='工种序列'),
        ),
        migrations.AlterField(
            model_name='opportunityteammember',
            name='role',
            field=models.CharField(choices=[('MEMBER', '普通成员'), ('SALES_REP', '销售经理'), ('PRE_SALES', '售前工程师'), ('PRODUCT', '产品经理'), ('TEST', '测试工程师'), ('IMPL', '实施工程师'), ('FRONTEND', '前端工程师'), ('BACKEND', '后端工程师'), ('UI', 'UI设计师'), ('GAME_ENGINEER', '春秋GAME工程师'), ('MARKETING_RND', '市场部研发人员'), ('LAB_XIAORANG', '霄壤实验室人员'), ('LAB_GAMMA', '伽玛实验室人员'), ('MANAGER', '部门经理'), ('DIRECTOR', '总监')], default='MEMBER', max_length=20, verbose_name='项目中角色'),
        ),
    ]
