# Generated by Django 4.2.27 on 2025-12-10 17:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0039_remove_userprofile_job_role_userprofile_job_level_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMediaAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=100, verbose_name='平台/应用名称')),
                ('account_username', models.CharField(max_length=100, verbose_name='社交媒体用户名')),
                ('password_hint', models.CharField(blank=True, max_length=200, verbose_name='密码提示(不保存明文)')),
                ('register_phone', models.CharField(blank=True, max_length=50, verbose_name='注册手机号')),
                ('credential_ref', models.CharField(blank=True, help_text='外部密码库引用ID（不保存明文）', max_length=100, verbose_name='凭据保管引用')),
                ('status', models.CharField(choices=[('DRAFT', '草稿'), ('PENDING', '待确认/审核中'), ('APPROVED', '已确认/已发布'), ('REJECTED', '已驳回')], default='PENDING', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '社媒账号管理',
                'verbose_name_plural': '社媒账号管理',
            },
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='job_position',
            field=models.CharField(blank=True, choices=[('PRODUCT_MANAGER', '产品经理'), ('FRONTEND', '前端'), ('BACKEND', '后端'), ('OPS', '运维'), ('UI', 'UI'), ('DESIGN', '设计'), ('COPYWRITER', '文案'), ('MEDIA', '媒介'), ('OPERATION', '运营'), ('RESEARCHER', '研究员'), ('M_GM', '总经理'), ('M_VGM', '副总经理'), ('M_DIRECTOR', '总监'), ('M_VDIRECTOR', '副总监'), ('M_SENIOR_MANAGER', '高级经理'), ('M_MANAGER', '经理'), ('S_INTERN', '实习生'), ('S_AE', '客户主任'), ('S_SAE', '高级客户主任'), ('S_AM', '客户经理'), ('S_SAM', '高级客户经理'), ('S_AD', '客户总监'), ('S_SAD', '高级客户总监')], max_length=30, null=True, verbose_name='岗位'),
        ),
        migrations.CreateModel(
            name='SocialMediaAdminHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='变更说明')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='变更时间')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_history', to='core.socialmediaaccount', verbose_name='社媒账号')),
                ('from_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='social_admin_from', to=settings.AUTH_USER_MODEL, verbose_name='原管理员')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='social_admin_operator', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('to_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='social_admin_to', to=settings.AUTH_USER_MODEL, verbose_name='新管理员')),
            ],
            options={
                'verbose_name': '社媒管理员变更历史',
                'verbose_name_plural': '社媒管理员变更历史',
            },
        ),
        migrations.CreateModel(
            name='SocialMediaAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_name', models.CharField(blank=True, max_length=100, verbose_name='管理员姓名')),
                ('admin_account_name', models.CharField(blank=True, max_length=100, verbose_name='管理员账号名')),
                ('admin_phone', models.CharField(blank=True, max_length=50, verbose_name='管理员手机号')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='任命时间')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='撤销时间')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_links', to='core.socialmediaaccount', verbose_name='社媒账号')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_admin_roles', to=settings.AUTH_USER_MODEL, verbose_name='管理员员工')),
            ],
            options={
                'verbose_name': '社媒管理员',
                'verbose_name_plural': '社媒管理员',
                'unique_together': {('account', 'user')},
            },
        ),
        migrations.AddField(
            model_name='socialmediaaccount',
            name='admins',
            field=models.ManyToManyField(related_name='managed_social_accounts', through='core.SocialMediaAdmin', to=settings.AUTH_USER_MODEL, verbose_name='管理员'),
        ),
        migrations.AddField(
            model_name='socialmediaaccount',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_social_accounts', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='socialmediastats',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='core.socialmediaaccount', verbose_name='关联社媒账号'),
        ),
        migrations.AlterUniqueTogether(
            name='socialmediaaccount',
            unique_together={('platform', 'account_username')},
        ),
    ]
