# Generated by Django 4.2.27 on 2025-12-10 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_socialmediaaccount_alter_userprofile_job_position_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmediastats',
            name='status',
            field=models.CharField(choices=[('DRAFT', '草稿'), ('PENDING', '待确认/审核中'), ('APPROVED', '已确认/已发布'), ('REJECTED', '已驳回')], default='APPROVED', max_length=20, verbose_name='状态'),
        ),
    ]
