# Generated by Django 4.2.27 on 2025-12-11 04:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0041_alter_socialmediastats_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='socialmediaaccount',
            unique_together={('platform', 'account_username')},
        ),
        migrations.AddField(
            model_name='socialmediaaccount',
            name='account_id',
            field=models.CharField(blank=True, max_length=120, verbose_name='账号唯一ID'),
        ),
        migrations.AddField(
            model_name='socialmediaaccount',
            name='display_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='对外显示名称'),
        ),
        migrations.AddField(
            model_name='socialmediaaccount',
            name='register_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='注册邮箱'),
        ),
        migrations.AlterField(
            model_name='socialmediaaccount',
            name='account_username',
            field=models.CharField(max_length=100, verbose_name='后台用户名'),
        ),
        migrations.AlterUniqueTogether(
            name='socialmediaaccount',
            unique_together={('platform', 'account_username'), ('platform', 'account_id')},
        ),
        migrations.CreateModel(
            name='SocialMediaAccountChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=100, verbose_name='变更字段')),
                ('old_value', models.CharField(blank=True, max_length=300, verbose_name='旧值')),
                ('new_value', models.CharField(blank=True, max_length=300, verbose_name='新值')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='变更时间')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_logs', to='core.socialmediaaccount', verbose_name='社媒账号')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
            ],
            options={
                'verbose_name': '社媒账号变更记录',
                'verbose_name_plural': '社媒账号变更记录',
            },
        ),
    ]
