# Generated by Django 4.2.27 on 2025-12-11 18:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0043_customertag_customer_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalIdMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('CUSTOMER', '客户'), ('CONTACT', '联系人'), ('OPPORTUNITY', '商机'), ('SOCIAL_ACCOUNT', '社媒账号')], max_length=30)),
                ('object_id', models.IntegerField()),
                ('system_name', models.CharField(max_length=50)),
                ('external_id', models.CharField(max_length=100)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '外部ID映射',
                'verbose_name_plural': '外部ID映射',
                'unique_together': {('system_name', 'external_id')},
            },
        ),
        migrations.CreateModel(
            name='CustomerCohort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('filters', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_cohorts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '客户分群',
                'verbose_name_plural': '客户分群',
            },
        ),
    ]
