# Generated by Django 4.2.27 on 2025-12-11 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_externalidmap_customercohort'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='region',
            field=models.CharField(blank=True, max_length=100, verbose_name='区域'),
        ),
    ]
