# Generated by Django 4.2.27 on 2025-12-12 10:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0046_alter_aiconfiguration_provider'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmissionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PARSED', '已解析'), ('SUBMITTED', '已提交'), ('FAILED', '提交失败')], default='PARSED', max_length=20, verbose_name='状态')),
                ('text_input', models.TextField(verbose_name='原始输入')),
                ('intent', models.CharField(blank=True, max_length=30, verbose_name='意图')),
                ('entity', models.CharField(blank=True, max_length=30, verbose_name='实体')),
                ('fields', models.JSONField(blank=True, default=dict, verbose_name='表单字段')),
                ('filters', models.JSONField(blank=True, default=dict, verbose_name='筛选条件')),
                ('result_payload', models.JSONField(blank=True, default=dict, verbose_name='执行结果')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submission_logs', to=settings.AUTH_USER_MODEL, verbose_name='提交人')),
            ],
            options={
                'verbose_name': 'AI提交日志',
                'verbose_name_plural': 'AI提交日志',
                'ordering': ['-created_at'],
            },
        ),
    ]
