# Generated by Django 4.2.27 on 2025-12-12 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_submissionlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='customer_company',
            field=models.CharField(blank=True, max_length=200, verbose_name='客户公司(文本)'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='customer_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='客户姓名(文本)'),
        ),
    ]
