# Generated by Django 4.2.27 on 2025-12-12 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_alter_opportunity_customer_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissionlog',
            name='error_message',
            field=models.TextField(blank=True, verbose_name='报错信息'),
        ),
        migrations.AddField(
            model_name='submissionlog',
            name='prompt',
            field=models.TextField(blank=True, verbose_name='完整Prompt'),
        ),
        migrations.AddField(
            model_name='submissionlog',
            name='raw_response',
            field=models.TextField(blank=True, verbose_name='AI原始返回'),
        ),
    ]
