# Generated by Django 4.2.27 on 2025-12-27 13:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0049_submissionlog_error_message_submissionlog_prompt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiconfiguration',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_configs', to=settings.AUTH_USER_MODEL, verbose_name='所属用户'),
        ),
    ]
