# Generated by Django 4.2.27 on 2025-12-27 13:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0050_aiconfiguration_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='项目名称')),
                ('code', models.CharField(help_text='例如：CUST-PROJ-001', max_length=50, unique=True, verbose_name='项目编号')),
                ('status', models.CharField(choices=[('PLANNING', '规划中'), ('IN_PROGRESS', '进行中'), ('COMPLETED', '已完成'), ('ARCHIVED', '已归档')], default='PLANNING', max_length=20, verbose_name='状态')),
                ('description', models.TextField(blank=True, verbose_name='项目描述')),
                ('budget', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='项目预算')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='开始日期')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='结束日期')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='core.customer', verbose_name='关联客户')),
                ('members', models.ManyToManyField(blank=True, related_name='participated_projects', to=settings.AUTH_USER_MODEL, verbose_name='项目成员')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_projects', to=settings.AUTH_USER_MODEL, verbose_name='负责人')),
            ],
            options={
                'verbose_name': '项目',
                'verbose_name_plural': '项目列表',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='卡片标题')),
                ('content', models.TextField(blank=True, verbose_name='内容详情')),
                ('status', models.CharField(choices=[('TODO', '待处理'), ('DOING', '进行中'), ('DONE', '已完成'), ('BLOCKED', '已阻塞')], default='TODO', max_length=20, verbose_name='状态')),
                ('budget', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='预算')),
                ('man_days', models.DecimalField(decimal_places=1, default=0, max_digits=6, verbose_name='工时(人天)')),
                ('progress', models.IntegerField(default=0, verbose_name='进度(%)')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='开始日期')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='截止日期')),
                ('is_milestone', models.BooleanField(default=False, verbose_name='是否里程碑')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('assignees', models.ManyToManyField(blank=True, related_name='assigned_cards', to=settings.AUTH_USER_MODEL, verbose_name='负责人')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.projectcard', verbose_name='父卡片')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='core.project', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': '项目卡片',
                'verbose_name_plural': '项目卡片',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
