# Generated by Django 4.2.27 on 2025-12-27 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_project_projectcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='extra_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='扩展数据'),
        ),
        migrations.AddField(
            model_name='projectcard',
            name='extra_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='扩展数据'),
        ),
    ]
