# Generated by Django 4.2.27 on 2025-12-27 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_alter_project_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectcard',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='是否启用'),
        ),
    ]
