# Generated by Django 4.2.27 on 2026-01-01 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_projectcard_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='collected_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='实际到账的金额', max_digits=12, verbose_name='已回款金额'),
        ),
    ]
