# Generated by Django 4.2.27 on 2026-01-01 15:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0055_opportunity_collected_amount'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='performancetarget',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='performancetarget',
            name='month',
            field=models.IntegerField(default=0, verbose_name='月份 (0代表不指定)'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='status',
            field=models.CharField(choices=[('ACTIVE', '进行中'), ('WON', '赢单'), ('LOST', '输单'), ('SUSPENDED', '商机暂停'), ('TERMINATED', '商机终止'), ('COMPLETED', '已完成')], default='ACTIVE', max_length=20, verbose_name='商机状态'),
        ),
        migrations.AlterUniqueTogether(
            name='performancetarget',
            unique_together={('year', 'quarter', 'month', 'department', 'user')},
        ),
    ]
