# Generated by Django 4.2.27 on 2026-01-01 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_alter_performancetarget_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='stage',
            field=models.CharField(choices=[('CONTACT', '接触阶段'), ('REQ_ANALYSIS', '需求分析'), ('INITIATION', '客户立项'), ('BIDDING', '招采阶段'), ('DELIVERY', '交付实施'), ('AFTER_SALES', '售后阶段'), ('COMPLETED', '项目完成'), ('SUSPENDED', '商机暂停'), ('TERMINATED', '商机终止')], default='CONTACT', max_length=20, verbose_name='当前阶段'),
        ),
    ]
