# Generated by Django 4.2.27 on 2026-01-01 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_alter_opportunity_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='opportunity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='core.opportunity', verbose_name='关联商机'),
        ),
    ]
