# Generated by Django 4.2.27 on 2026-01-01 17:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0058_project_opportunity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('PLANNING', '规划中'), ('IN_PROGRESS', '进行中'), ('COMPLETED', '已完成'), ('ARCHIVED', '已归档'), ('TERMINATED', '已中止')], default='PLANNING', max_length=20, verbose_name='状态'),
        ),
        migrations.CreateModel(
            name='ProjectChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=50, verbose_name='变更字段')),
                ('old_value', models.TextField(blank=True, verbose_name='旧值')),
                ('new_value', models.TextField(blank=True, verbose_name='新值')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='变更时间')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_logs', to='core.project', verbose_name='关联项目')),
            ],
            options={
                'verbose_name': '项目变更日志',
                'verbose_name_plural': '项目变更日志',
                'ordering': ['-created_at'],
            },
        ),
    ]
