# Generated by Django 4.2.27 on 2026-01-01 18:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0059_alter_project_status_projectchangelog'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日期')),
                ('raw_content', models.TextField(help_text='用户输入的原始记录', verbose_name='原始工作内容')),
                ('polished_content', models.TextField(blank=True, help_text='AI优化后的总结', verbose_name='AI润色内容')),
                ('status', models.CharField(choices=[('DRAFT', '草稿'), ('SUBMITTED', '已提交')], default='DRAFT', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('projects', models.ManyToManyField(blank=True, related_name='daily_reports', to='core.project', verbose_name='关联项目')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_reports', to=settings.AUTH_USER_MODEL, verbose_name='填写人')),
            ],
            options={
                'verbose_name': '工作日报',
                'verbose_name_plural': '工作日报',
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='socialmediaadmin',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='socialmediaadmin',
            name='account',
        ),
        migrations.RemoveField(
            model_name='socialmediaadmin',
            name='user',
        ),
        migrations.RemoveField(
            model_name='socialmediaadminhistory',
            name='account',
        ),
        migrations.RemoveField(
            model_name='socialmediaadminhistory',
            name='from_user',
        ),
        migrations.RemoveField(
            model_name='socialmediaadminhistory',
            name='operator',
        ),
        migrations.RemoveField(
            model_name='socialmediaadminhistory',
            name='to_user',
        ),
        migrations.AlterModelOptions(
            name='approvalrequest',
            options={'ordering': ['-created_at'], 'verbose_name': '审批申请', 'verbose_name_plural': '审批申请'},
        ),
        migrations.AlterModelOptions(
            name='competition',
            options={'ordering': ['-start_date'], 'verbose_name': '行业赛事', 'verbose_name_plural': '行业赛事'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': '联系人', 'verbose_name_plural': '联系人列表'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['-created_at'], 'verbose_name': '客户', 'verbose_name_plural': '客户列表'},
        ),
        migrations.AlterModelOptions(
            name='departmentmodel',
            options={'verbose_name': '部门', 'verbose_name_plural': '部门管理'},
        ),
        migrations.AlterModelOptions(
            name='marketactivity',
            options={'ordering': ['-date'], 'verbose_name': '市场活动', 'verbose_name_plural': '市场活动'},
        ),
        migrations.AlterModelOptions(
            name='opportunitylog',
            options={'ordering': ['-created_at'], 'verbose_name': '跟进日志', 'verbose_name_plural': '跟进日志'},
        ),
        migrations.AlterModelOptions(
            name='opportunityteammember',
            options={'verbose_name': '团队成员', 'verbose_name_plural': '团队成员'},
        ),
        migrations.AlterModelOptions(
            name='performancetarget',
            options={'verbose_name': '业绩指标', 'verbose_name_plural': '业绩指标'},
        ),
        migrations.AlterModelOptions(
            name='socialmediaaccount',
            options={'verbose_name': '社媒账号', 'verbose_name_plural': '社媒账号'},
        ),
        migrations.AlterModelOptions(
            name='socialmediastats',
            options={'ordering': ['-date'], 'verbose_name': '社媒数据', 'verbose_name_plural': '社媒数据'},
        ),
        migrations.AlterModelOptions(
            name='todotask',
            options={'ordering': ['is_completed', '-priority', 'deadline'], 'verbose_name': '待办事项', 'verbose_name_plural': '待办事项'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={},
        ),
        migrations.AlterModelOptions(
            name='workreport',
            options={'ordering': ['-start_date'], 'verbose_name': '工作报告', 'verbose_name_plural': '工作报告'},
        ),
        migrations.AlterUniqueTogether(
            name='performancetarget',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='socialmediaaccount',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='target_departments',
        ),
        migrations.RemoveField(
            model_name='competition',
            name='ai_raw_text',
        ),
        migrations.RemoveField(
            model_name='competition',
            name='challenge_type',
        ),
        migrations.RemoveField(
            model_name='competition',
            name='confirmed_by',
        ),
        migrations.RemoveField(
            model_name='competition',
            name='contact_person',
        ),
        migrations.RemoveField(
            model_name='competition',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='competition',
            name='department_name',
        ),
        migrations.RemoveField(
            model_name='competition',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='competition',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='competition',
            name='format',
        ),
        migrations.RemoveField(
            model_name='competition',
            name='host_type',
        ),
        migrations.RemoveField(
            model_name='competition',
            name='impact_level',
        ),
        migrations.RemoveField(
            model_name='competition',
            name='industry',
        ),
        migrations.RemoveField(
            model_name='competition',
            name='leader_count',
        ),
        migrations.RemoveField(
            model_name='competition',
            name='level',
        ),
        migrations.RemoveField(
            model_name='competition',
            name='organizers',
        ),
        migrations.RemoveField(
            model_name='competition',
            name='owner_name',
        ),
        migrations.RemoveField(
            model_name='competition',
            name='participant_count',
        ),
        migrations.RemoveField(
            model_name='competition',
            name='project_code',
        ),
        migrations.RemoveField(
            model_name='competition',
            name='project_name',
        ),
        migrations.RemoveField(
            model_name='competition',
            name='scale',
        ),
        migrations.RemoveField(
            model_name='competition',
            name='system_format',
        ),
        migrations.RemoveField(
            model_name='competition',
            name='target_audience',
        ),
        migrations.RemoveField(
            model_name='competition',
            name='team_count',
        ),
        migrations.RemoveField(
            model_name='competition',
            name='time',
        ),
        migrations.RemoveField(
            model_name='competition',
            name='type',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='department',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='is_decision_maker',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='wechat',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='ai_raw_text',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='legal_representative',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='registered_capital',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='scale',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='status',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='departmentmodel',
            name='description',
        ),
        migrations.RemoveField(
            model_name='departmentmodel',
            name='order',
        ),
        migrations.RemoveField(
            model_name='marketactivity',
            name='ai_raw_text',
        ),
        migrations.RemoveField(
            model_name='marketactivity',
            name='confirmed_by',
        ),
        migrations.RemoveField(
            model_name='marketactivity',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='marketactivity',
            name='scale',
        ),
        migrations.RemoveField(
            model_name='marketactivity',
            name='status',
        ),
        migrations.RemoveField(
            model_name='marketactivity',
            name='time',
        ),
        migrations.RemoveField(
            model_name='marketactivity',
            name='type',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='ai_raw_text',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='approval_status',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='customer_industry',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='customer_org',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='customer_phone',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='customer_region',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='expected_sign_date',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='gross_profit',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='is_confirmed_by_sales',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='product_line',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='project_manager',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='revenue',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='signed_amount',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='source',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='status',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='win_rate',
        ),
        migrations.RemoveField(
            model_name='opportunitylog',
            name='stage_snapshot',
        ),
        migrations.RemoveField(
            model_name='todotask',
            name='assignee',
        ),
        migrations.RemoveField(
            model_name='todotask',
            name='completed_at',
        ),
        migrations.RemoveField(
            model_name='todotask',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='todotask',
            name='object_id',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='job_series',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='reports_to',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='wechat_openid',
        ),
        migrations.RemoveField(
            model_name='workreport',
            name='ai_raw_input',
        ),
        migrations.RemoveField(
            model_name='workreport',
            name='ai_summary',
        ),
        migrations.RemoveField(
            model_name='workreport',
            name='related_opportunities',
        ),
        migrations.RemoveField(
            model_name='workreport',
            name='report_date',
        ),
        migrations.RemoveField(
            model_name='workreport',
            name='type',
        ),
        migrations.AddField(
            model_name='announcement',
            name='department',
            field=models.CharField(blank=True, choices=[('SALES', '销售部门'), ('POC', '交付/实施/POC'), ('RND', '研发中心'), ('MARKETING', '市场部'), ('HR', '人力资源'), ('FINANCE', '财务部'), ('OTHER', '其他')], max_length=20, null=True, verbose_name='所属部门'),
        ),
        migrations.AddField(
            model_name='approvalrequest',
            name='feedback',
            field=models.TextField(blank=True, verbose_name='审批意见'),
        ),
        migrations.AddField(
            model_name='approvalrequest',
            name='request_type',
            field=models.CharField(choices=[('DATA_MODIFICATION', '数据修改'), ('DELETE_REQUEST', '删除申请'), ('BUDGET', '预算审批'), ('OTHER', '其他')], default='OTHER', max_length=20, verbose_name='申请类型'),
        ),
        migrations.AddField(
            model_name='competition',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='结束日期'),
        ),
        migrations.AddField(
            model_name='competition',
            name='organizer',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='主办方'),
        ),
        migrations.AddField(
            model_name='competition',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='开始日期'),
        ),
        migrations.AddField(
            model_name='competition',
            name='website',
            field=models.URLField(blank=True, verbose_name='官网'),
        ),
        migrations.AddField(
            model_name='contact',
            name='attitude',
            field=models.CharField(blank=True, help_text='例如：支持、中立、反对', max_length=50, verbose_name='态度'),
        ),
        migrations.AddField(
            model_name='contact',
            name='decision_role',
            field=models.CharField(blank=True, help_text='例如：决策者、影响者、使用者、把关人', max_length=50, verbose_name='决策角色'),
        ),
        migrations.AddField(
            model_name='contact',
            name='is_primary',
            field=models.BooleanField(default=False, verbose_name='是否主要联系人'),
        ),
        migrations.AddField(
            model_name='contact',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='customer',
            name='description',
            field=models.TextField(blank=True, verbose_name='备注'),
        ),
        migrations.AddField(
            model_name='customertag',
            name='customers',
            field=models.ManyToManyField(blank=True, related_name='tags', to='core.customer', verbose_name='关联客户'),
        ),
        migrations.AddField(
            model_name='marketactivity',
            name='actual_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='实际花费'),
        ),
        migrations.AddField(
            model_name='marketactivity',
            name='budget',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='预算'),
        ),
        migrations.AddField(
            model_name='marketactivity',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='活动日期'),
        ),
        migrations.AddField(
            model_name='marketactivity',
            name='leads_count',
            field=models.IntegerField(default=0, verbose_name='获客数量'),
        ),
        migrations.AddField(
            model_name='marketactivity',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='负责人'),
        ),
        migrations.AddField(
            model_name='marketactivity',
            name='participants',
            field=models.IntegerField(default=0, verbose_name='预计人数'),
        ),
        migrations.AddField(
            model_name='opportunityteammember',
            name='joined_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='加入时间'),
        ),
        migrations.AddField(
            model_name='performancetarget',
            name='period',
            field=models.CharField(choices=[('MONTH', '月度'), ('QUARTER', '季度'), ('YEAR', '年度')], default='YEAR', max_length=20, verbose_name='周期类型'),
        ),
        migrations.AddField(
            model_name='performancetarget',
            name='target_type',
            field=models.CharField(choices=[('INDIVIDUAL', '个人'), ('DEPARTMENT', '部门'), ('COMPANY', '公司')], default='INDIVIDUAL', max_length=20, verbose_name='指标类型'),
        ),
        migrations.AddField(
            model_name='socialmediaaccount',
            name='account_name',
            field=models.CharField(default='', max_length=100, verbose_name='账号名称'),
        ),
        migrations.AddField(
            model_name='socialmediaaccount',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='负责人'),
        ),
        migrations.AddField(
            model_name='socialmediaaccount',
            name='url',
            field=models.URLField(blank=True, verbose_name='主页链接'),
        ),
        migrations.AddField(
            model_name='socialmediastats',
            name='content_count',
            field=models.IntegerField(default=0, verbose_name='发布内容数'),
        ),
        migrations.AddField(
            model_name='socialmediastats',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='统计日期'),
        ),
        migrations.AddField(
            model_name='socialmediastats',
            name='fans_growth',
            field=models.IntegerField(default=0, verbose_name='粉丝增量'),
        ),
        migrations.AddField(
            model_name='socialmediastats',
            name='interaction_count',
            field=models.IntegerField(default=0, verbose_name='互动量(转评赞)'),
        ),
        migrations.AddField(
            model_name='socialmediastats',
            name='read_count',
            field=models.IntegerField(default=0, verbose_name='阅读/播放量'),
        ),
        migrations.AddField(
            model_name='todotask',
            name='priority',
            field=models.CharField(choices=[('HIGH', '高'), ('MEDIUM', '中'), ('LOW', '低')], default='MEDIUM', max_length=10, verbose_name='优先级'),
        ),
        migrations.AddField(
            model_name='todotask',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='todotask',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to=settings.AUTH_USER_MODEL, verbose_name='所属用户'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='手机号'),
        ),
        migrations.AddField(
            model_name='workreport',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='结束日期'),
        ),
        migrations.AddField(
            model_name='workreport',
            name='plan_next',
            field=models.TextField(blank=True, verbose_name='下阶段计划'),
        ),
        migrations.AddField(
            model_name='workreport',
            name='report_type',
            field=models.CharField(choices=[('WEEKLY', '周报'), ('MONTHLY', '月报')], default='WEEKLY', max_length=10, verbose_name='报告类型'),
        ),
        migrations.AddField(
            model_name='workreport',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='开始日期'),
        ),
        migrations.AlterField(
            model_name='approvalrequest',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_requests', to=settings.AUTH_USER_MODEL, verbose_name='申请人'),
        ),
        migrations.AlterField(
            model_name='approvalrequest',
            name='approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_approvals', to=settings.AUTH_USER_MODEL, verbose_name='审批人'),
        ),
        migrations.AlterField(
            model_name='approvalrequest',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        # migrations.AlterField(
        #     model_name='approvalrequest',
        #     name='object_id',
        #     field=models.PositiveIntegerField(blank=True, null=True),
        # ),
        migrations.AlterField(
            model_name='approvalrequest',
            name='reason',
            field=models.TextField(blank=True, default='', verbose_name='申请详情/原因'),
        ),
        migrations.AlterField(
            model_name='approvalrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', '待审批'), ('APPROVED', '已通过'), ('REJECTED', '已拒绝')], default='PENDING', max_length=20, verbose_name='状态'),
        ),
        # migrations.AlterField(
        #     model_name='competition',
        #     name='challenge_count',
        #     field=models.IntegerField(default=0, verbose_name='赛题数量'),
        # ),
        migrations.AlterField(
            model_name='competition',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='competition',
            name='description',
            field=models.TextField(blank=True, verbose_name='详情描述'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='location',
            field=models.CharField(blank=True, max_length=100, verbose_name='地点'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='name',
            field=models.CharField(max_length=200, verbose_name='赛事名称'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='status',
            field=models.CharField(choices=[('UPCOMING', '即将开始'), ('REGISTRATION', '报名中'), ('ONGOING', '进行中'), ('ENDED', '已结束')], default='UPCOMING', max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='ai_raw_text',
            field=models.TextField(blank=True, verbose_name='AI分析原始文本'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=50, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='电话'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='title',
            field=models.CharField(blank=True, max_length=50, verbose_name='职务'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(blank=True, max_length=200, verbose_name='地址'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.CharField(blank=True, help_text='例如：CUST-001', max_length=50, null=True, unique=True, verbose_name='客户编号'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='industry',
            field=models.CharField(blank=True, max_length=50, verbose_name='所属行业'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=100, verbose_name='客户名称'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customers', to=settings.AUTH_USER_MODEL, verbose_name='负责人'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='region',
            field=models.CharField(blank=True, help_text='例如：华北、华东、海外', max_length=50, verbose_name='所属区域'),
        ),
        migrations.AlterField(
            model_name='departmentmodel',
            name='category',
            field=models.CharField(choices=[('SALES', '销售部门'), ('POC', '交付/实施/POC'), ('RND', '研发中心'), ('MARKETING', '市场部'), ('HR', '人力资源'), ('FINANCE', '财务部'), ('OTHER', '其他')], default='OTHER', max_length=20, verbose_name='部门性质'),
        ),
        migrations.AlterField(
            model_name='marketactivity',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='marketactivity',
            name='location',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='地点'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='预计金额'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='collected_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='已回款金额'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='competitors',
            field=models.TextField(blank=True, verbose_name='竞争对手'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_opportunities', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='opportunities', to='core.customer', verbose_name='客户'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='customer_code',
            field=models.CharField(blank=True, max_length=50, verbose_name='客户编号'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='customer_company',
            field=models.CharField(blank=True, help_text='若未关联客户实体，可直接填写公司名', max_length=100, verbose_name='客户公司名称'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='customer_contact_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='联系人姓名'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='customer_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='联系人邮箱'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='description',
            field=models.TextField(blank=True, verbose_name='商机描述'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='profit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='预计利润'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='sales_manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='managed_opportunities', to=settings.AUTH_USER_MODEL, verbose_name='销售负责人'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='stage',
            field=models.CharField(choices=[('CONTACT', '接触阶段 (10%)'), ('REQ_ANALYSIS', '需求分析 (30%)'), ('INITIATION', '客户立项 (50%)'), ('BIDDING', '招采阶段 (70%)'), ('DELIVERY', '交付实施 (90%)'), ('AFTER_SALES', '售后阶段 (100%)'), ('COMPLETED', '项目完成 (100%)'), ('SUSPENDED', '商机暂停 (0%)'), ('TERMINATED', '商机终止 (0%)'), ('WON', '赢单 (100%)'), ('LOST', '输单 (0%)')], default='CONTACT', max_length=20, verbose_name='阶段'),
        ),
        # migrations.AlterField(
        #     model_name='opportunity',
        #     name='team_members',
        #     field=models.ManyToManyField(related_name='participated_opportunities', through='core.OpportunityTeamMember', to=settings.AUTH_USER_MODEL, verbose_name='团队成员'),
        # ),
        migrations.AlterField(
            model_name='opportunitylog',
            name='action',
            field=models.CharField(help_text='例如：电话沟通、拜访、方案汇报', max_length=50, verbose_name='动作'),
        ),
        migrations.AlterField(
            model_name='opportunitylog',
            name='content',
            field=models.TextField(verbose_name='内容详情'),
        ),
        migrations.AlterField(
            model_name='opportunitylog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='opportunitylog',
            name='opportunity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='core.opportunity', verbose_name='商机'),
        ),
        migrations.AlterField(
            model_name='opportunitylog',
            name='transfer_target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_transfers', to=settings.AUTH_USER_MODEL, verbose_name='移交给'),
        ),
        migrations.AlterField(
            model_name='opportunityteammember',
            name='opportunity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.opportunity', verbose_name='商机'),
        ),
        migrations.AlterField(
            model_name='opportunityteammember',
            name='role',
            field=models.CharField(choices=[('SALES', '销售'), ('PRE_SALES', '售前/方案'), ('SOLUTION', '解决方案专家'), ('DELIVERY', '交付/实施'), ('PM', '项目经理'), ('PDM', '产品经理'), ('RND', '研发'), ('QA', '测试'), ('OTHER', '其他')], default='OTHER', max_length=20, verbose_name='角色'),
        ),
        migrations.AlterField(
            model_name='opportunityteammember',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AlterField(
            model_name='opportunitytransferapplication',
            name='status',
            field=models.CharField(choices=[('PENDING', '待审批'), ('APPROVED', '已通过'), ('REJECTED', '已拒绝')], default='PENDING', max_length=20, verbose_name='审批状态'),
        ),
        migrations.AlterField(
            model_name='performancetarget',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        # migrations.AlterField(
        #     model_name='performancetarget',
        #     name='department',
        #     field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.departmentmodel', verbose_name='负责部门'),
        # ),
        migrations.AlterField(
            model_name='performancetarget',
            name='month',
            field=models.IntegerField(blank=True, null=True, verbose_name='月份(仅月度)'),
        ),
        migrations.AlterField(
            model_name='performancetarget',
            name='quarter',
            field=models.IntegerField(blank=True, null=True, verbose_name='季度(仅季度)'),
        ),
        migrations.AlterField(
            model_name='performancetarget',
            name='target_amount',
            field=models.DecimalField(decimal_places=2, max_digits=14, verbose_name='目标金额'),
        ),
        migrations.AlterField(
            model_name='performancetarget',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        # migrations.AlterField(
        #     model_name='performancetarget',
        #     name='user',
        #     field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='负责人'),
        # ),
        migrations.AlterField(
            model_name='performancetarget',
            name='year',
            field=models.IntegerField(verbose_name='年份'),
        ),
        migrations.AlterField(
            model_name='socialmediaaccount',
            name='account_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='账号ID/Handle'),
        ),
        migrations.AlterField(
            model_name='socialmediaaccount',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='socialmediaaccount',
            name='platform',
            field=models.CharField(choices=[('WECHAT_OFFICIAL', '微信公众号'), ('WECHAT_VIDEO', '微信视频号'), ('DOUYIN', '抖音'), ('BILIBILI', 'Bilibili'), ('WEIBO', '微博'), ('XIAOHONGSHU', '小红书'), ('OTHER', '其他')], default='OTHER', max_length=20, verbose_name='平台'),
        ),
        # migrations.AlterField(
        #     model_name='socialmediastats',
        #     name='account',
        #     field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='core.socialmediaaccount', verbose_name='账号'),
        # ),
        migrations.AlterField(
            model_name='socialmediastats',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='提交时间'),
        ),
        migrations.AlterField(
            model_name='socialmediastats',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_stats', to=settings.AUTH_USER_MODEL, verbose_name='提交人'),
        ),
        migrations.AlterField(
            model_name='socialmediastats',
            name='status',
            field=models.CharField(choices=[('DRAFT', '草稿'), ('PENDING', '待审核'), ('APPROVED', '已审核'), ('REJECTED', '已驳回')], default='DRAFT', max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='todotask',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='todotask',
            name='source_type',
            field=models.CharField(choices=[('MANUAL', '手动创建'), ('AI_GENERATED', 'AI生成'), ('SYSTEM', '系统触发')], default='MANUAL', max_length=20, verbose_name='来源类型'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='department',
            field=models.CharField(blank=True, max_length=50, verbose_name='部门(旧)'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='job_level',
            field=models.CharField(blank=True, default='', help_text='例如：P5, P6, M1', max_length=20, verbose_name='职级'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='job_position',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='职位'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workreport',
            name='content',
            field=models.TextField(verbose_name='报告内容'),
        ),
        migrations.AlterField(
            model_name='workreport',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='workreport',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to=settings.AUTH_USER_MODEL, verbose_name='提交人'),
        ),
        migrations.AlterUniqueTogether(
            name='opportunityteammember',
            unique_together={('opportunity', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='performancetarget',
            unique_together={('target_type', 'period', 'year', 'month', 'quarter', 'user', 'department')},
        ),
        migrations.AlterUniqueTogether(
            name='socialmediaaccount',
            unique_together={('platform', 'account_name')},
        ),
        migrations.AlterUniqueTogether(
            name='socialmediastats',
            unique_together={('account', 'date')},
        ),
        migrations.DeleteModel(
            name='SocialMediaAccountChangeLog',
        ),
        migrations.DeleteModel(
            name='SocialMediaAdminHistory',
        ),
        migrations.RemoveField(
            model_name='opportunityteammember',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='opportunityteammember',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='opportunityteammember',
            name='name',
        ),
        migrations.RemoveField(
            model_name='opportunityteammember',
            name='responsibility',
        ),
        migrations.RemoveField(
            model_name='opportunityteammember',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='opportunityteammember',
            name='workload',
        ),
        migrations.RemoveField(
            model_name='performancetarget',
            name='target_gross_profit',
        ),
        migrations.RemoveField(
            model_name='performancetarget',
            name='target_revenue',
        ),
        migrations.RemoveField(
            model_name='socialmediaaccount',
            name='account_username',
        ),
        migrations.RemoveField(
            model_name='socialmediaaccount',
            name='admins',
        ),
        migrations.RemoveField(
            model_name='socialmediaaccount',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='socialmediaaccount',
            name='credential_ref',
        ),
        migrations.RemoveField(
            model_name='socialmediaaccount',
            name='display_name',
        ),
        migrations.RemoveField(
            model_name='socialmediaaccount',
            name='password_hint',
        ),
        migrations.RemoveField(
            model_name='socialmediaaccount',
            name='register_email',
        ),
        migrations.RemoveField(
            model_name='socialmediaaccount',
            name='register_phone',
        ),
        migrations.RemoveField(
            model_name='socialmediaaccount',
            name='status',
        ),
        migrations.RemoveField(
            model_name='socialmediaaccount',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='socialmediastats',
            name='platform',
        ),
        migrations.RemoveField(
            model_name='socialmediastats',
            name='record_date',
        ),
        migrations.RemoveField(
            model_name='socialmediastats',
            name='updated_at',
        ),
        migrations.DeleteModel(
            name='SocialMediaAdmin',
        ),
    ]
