# Generated by Django 4.2.27 on 2026-01-01 18:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0060_dailyreport_alter_socialmediaadmin_unique_together_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='approvalrequest',
                    name='object_id',
                    field=models.PositiveIntegerField(blank=True, null=True),
                ),
                migrations.AlterField(
                    model_name='competition',
                    name='challenge_count',
                    field=models.IntegerField(default=0, verbose_name='赛题数量'),
                ),
                migrations.AlterField(
                    model_name='opportunity',
                    name='team_members',
                    field=models.ManyToManyField(related_name='participated_opportunities', through='core.OpportunityTeamMember', to=settings.AUTH_USER_MODEL, verbose_name='团队成员'),
                ),
                migrations.AlterField(
                    model_name='performancetarget',
                    name='department',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.departmentmodel', verbose_name='负责部门'),
                ),
                migrations.AlterField(
                    model_name='performancetarget',
                    name='user',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='负责人'),
                ),
                migrations.AlterField(
                    model_name='socialmediastats',
                    name='account',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='core.socialmediaaccount', verbose_name='账号'),
                ),
            ],
            database_operations=[],
        ),
    ]
