# Generated by Django 4.2.27 on 2026-01-01 20:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0061_alter_approvalrequest_object_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyreport',
            name='mentions',
            field=models.ManyToManyField(blank=True, related_name='mentioned_reports', to=settings.AUTH_USER_MODEL, verbose_name='提及用户'),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='title',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='标题'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('type', models.CharField(choices=[('SYSTEM', '系统通知'), ('MENTION', '提及通知'), ('APPROVAL', '审批通知'), ('TASK', '任务提醒')], default='SYSTEM', max_length=20, verbose_name='类型')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False, verbose_name='已读')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='接收人')),
            ],
            options={
                'verbose_name': '系统通知',
                'verbose_name_plural': '系统通知',
                'ordering': ['-created_at'],
            },
        ),
    ]
