# Generated by Django 4.2.27 on 2026-01-02 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_dailyreport_mentions_dailyreport_title_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('SYSTEM', '系统通知'), ('NORMAL', '普通消息'), ('MENTION', '提及通知'), ('APPROVAL', '审批通知'), ('TASK', '任务提醒')], default='SYSTEM', max_length=20, verbose_name='类型'),
        ),
    ]
