# Generated by Django 4.2.27 on 2026-01-02 04:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0063_alter_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='report_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates_profiles', to=settings.AUTH_USER_MODEL, verbose_name='汇报对象'),
        ),
    ]
