# Generated by Django 4.2.27 on 2026-01-02 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_userprofile_report_to'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='performancetarget',
                    name='department',
                    field=models.ForeignKey(blank=True, db_column='department', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.departmentmodel', verbose_name='负责部门'),
                ),
            ],
            database_operations=[],
        ),
    ]
