# Generated by Django 4.2.27 on 2026-01-02 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0066_migrate_performance_department_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='auto_update_progress',
            field=models.BooleanField(default=True, help_text='勾选则根据卡片自动计算', verbose_name='自动更新进度'),
        ),
        migrations.AddField(
            model_name='project',
            name='followup_rhythm',
            field=models.CharField(choices=[('DAILY', '每日跟进'), ('WEEKLY', '每周跟进'), ('BIWEEKLY', '两周一跟'), ('MONTHLY', '每月跟进'), ('AS_NEEDED', '按需跟进')], default='WEEKLY', max_length=20, verbose_name='跟进节奏'),
        ),
        migrations.AddField(
            model_name='project',
            name='is_fully_paid',
            field=models.BooleanField(default=False, verbose_name='完全回款'),
        ),
        migrations.AddField(
            model_name='project',
            name='is_maintenance_finished',
            field=models.BooleanField(default=False, verbose_name='维保完成'),
        ),
        migrations.AddField(
            model_name='project',
            name='is_revenue_confirmed',
            field=models.BooleanField(default=False, verbose_name='已经确收'),
        ),
        migrations.AddField(
            model_name='project',
            name='progress_manual',
            field=models.IntegerField(default=0, verbose_name='手动进度(%)'),
        ),
        migrations.AddField(
            model_name='project',
            name='stage',
            field=models.CharField(choices=[('OPPORTUNITY', '商机阶段'), ('PROPOSAL', '规划阶段'), ('INITIATION', '立项阶段'), ('CONTRACT_SIGNED', '已签合同'), ('IMPLEMENTING', '实施阶段'), ('ACCEPTANCE', '验收阶段'), ('AFTER_SALES', '售后阶段'), ('PAYMENT_IN_PROGRESS', '回款推进中'), ('ARCHIVED', '已归档')], default='OPPORTUNITY', max_length=30, verbose_name='具体阶段'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('PLANNING', '规划中'), ('IN_PROGRESS', '进行中'), ('COMPLETED', '已完成'), ('PAUSED', '项目暂停'), ('TERMINATED', '项目终止')], default='PLANNING', max_length=20, verbose_name='状态'),
        ),
    ]
