# Generated by Django 4.2.27 on 2026-01-03 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0067_project_auto_update_progress_project_followup_rhythm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectcard',
            name='sub_stage',
            field=models.CharField(blank=True, help_text='例如：设计中、开发中、测试中', max_length=50, verbose_name='子项目阶段'),
        ),
    ]
