# Generated by Django 4.2.27 on 2026-01-04 07:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0068_projectcard_sub_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', '待审批'), ('APPROVED', '已通过'), ('REJECTED', '已拒绝'), ('DRAFT', '草稿')], default='PENDING', max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AlterField(
            model_name='opportunitytransferapplication',
            name='status',
            field=models.CharField(choices=[('PENDING', '待审批'), ('APPROVED', '已通过'), ('REJECTED', '已拒绝'), ('DRAFT', '草稿')], default='PENDING', max_length=20, verbose_name='审批状态'),
        ),
        migrations.AlterField(
            model_name='socialmediastats',
            name='status',
            field=models.CharField(choices=[('PENDING', '待审批'), ('APPROVED', '已通过'), ('REJECTED', '已拒绝'), ('DRAFT', '草稿')], default='DRAFT', max_length=20, verbose_name='状态'),
        ),
    ]
