# Generated by Django 4.2.27 on 2026-01-05 08:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0069_alter_approvalrequest_status_alter_dailyreport_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectchangelog',
            name='action',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='动作'),
        ),
        migrations.AddField(
            model_name='projectchangelog',
            name='content',
            field=models.TextField(blank=True, default='', verbose_name='内容详情'),
        ),
        migrations.AlterField(
            model_name='project',
            name='stage',
            field=models.CharField(choices=[('OPPORTUNITY', '商机阶段'), ('PROPOSAL', '规划阶段'), ('INITIATION', '立项阶段'), ('CONTRACT_SIGNED', '已签合同'), ('IMPLEMENTING', '实施阶段'), ('ACCEPTANCE', '验收阶段'), ('AFTER_SALES', '售后阶段'), ('PAYMENT_IN_PROGRESS', '已经回款'), ('ARCHIVED', '已归档')], default='OPPORTUNITY', max_length=30, verbose_name='具体阶段'),
        ),
        migrations.AlterField(
            model_name='projectchangelog',
            name='field_name',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='变更字段'),
        ),
        migrations.AlterField(
            model_name='projectchangelog',
            name='new_value',
            field=models.TextField(blank=True, default='', verbose_name='新值'),
        ),
        migrations.AlterField(
            model_name='projectchangelog',
            name='old_value',
            field=models.TextField(blank=True, default='', verbose_name='旧值'),
        ),
        migrations.CreateModel(
            name='ContactDeleteLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(max_length=100, verbose_name='原联系人姓名')),
                ('customer_name', models.CharField(max_length=200, verbose_name='所属客户')),
                ('deleted_at', models.DateTimeField(auto_now_add=True, verbose_name='删除时间')),
                ('original_data', models.JSONField(verbose_name='原始数据备份')),
                ('is_restored', models.BooleanField(default=False, verbose_name='是否已恢复')),
                ('deleted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='删除人')),
            ],
            options={
                'verbose_name': '联系人删除日志',
                'verbose_name_plural': '联系人删除日志',
                'ordering': ['-deleted_at'],
            },
        ),
    ]
