# Generated by Django 4.2.27 on 2026-01-05 15:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0070_projectchangelog_action_projectchangelog_content_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="activitylog",
            name="department",
            field=models.CharField(blank=True, max_length=100, verbose_name="操作人部门"),
        ),
        migrations.AddField(
            model_name="performancetarget",
            name="target_gross_profit",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=14, verbose_name="毛利目标"
            ),
        ),
        migrations.AddField(
            model_name="performancetarget",
            name="target_revenue",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=14, verbose_name="营收目标"
            ),
        ),
        migrations.AlterField(
            model_name="activitylog",
            name="action",
            field=models.CharField(max_length=50, verbose_name="行为类型"),
        ),
        migrations.AlterField(
            model_name="activitylog",
            name="actor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="操作人",
            ),
        ),
        migrations.AlterField(
            model_name="activitylog",
            name="content",
            field=models.TextField(verbose_name="日志内容"),
        ),
        migrations.AlterField(
            model_name="activitylog",
            name="type",
            field=models.CharField(
                choices=[
                    ("OPPORTUNITY", "商机"),
                    ("CUSTOMER", "客户"),
                    ("CONTACT", "联系人"),
                    ("ACTIVITY", "活动"),
                    ("COMPETITION", "赛事"),
                    ("PROJECT", "项目"),
                    ("DAILY_REPORT", "日报"),
                    ("SYSTEM", "系统"),
                    ("USER", "用户"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="performancetarget",
            name="target_amount",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=14, verbose_name="目标金额"
            ),
        ),
    ]
