# Generated by Django 4.2.27 on 2026-01-05 16:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0071_activitylog_department_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="performancetarget",
            name="target_amount",
        ),
        migrations.AddField(
            model_name="performancetarget",
            name="target_contract_amount",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=14, verbose_name="新签合同目标"
            ),
        ),
        migrations.AlterField(
            model_name="performancetarget",
            name="target_gross_profit",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=14, verbose_name="回款毛利目标"
            ),
        ),
        migrations.AlterField(
            model_name="performancetarget",
            name="target_revenue",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=14, verbose_name="确认收入目标"
            ),
        ),
    ]
