# Generated by Django 4.2.27 on 2026-01-06 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0072_remove_performancetarget_target_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='job_category',
            field=models.CharField(choices=[('MANAGEMENT', '管理'), ('RND', '研发'), ('SALES', '销售'), ('RESEARCHER', '研究员'), ('MARKETING', '市场'), ('OPERATION', '运营'), ('DESIGN', '设计'), ('SYSADMIN', '系统管理员'), ('ASSISTANT', '助理'), ('OTHER', '其他')], default='OTHER', max_length=20, verbose_name='岗位属性'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='job_rank',
            field=models.CharField(blank=True, choices=[('ASSISTANT', '助理'), ('SPECIALIST', '专员'), ('SUPERVISOR', '主任'), ('MANAGER', '经理'), ('DIRECTOR', '总监'), ('DEPUTY_DIRECTOR', '副总监'), ('VP', '副总裁'), ('SVP', '高级副总裁/助理总裁'), ('PRESIDENT', '总裁')], max_length=20, verbose_name='职级'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='job_rank_level',
            field=models.CharField(choices=[('NORMAL', '普通'), ('SENIOR', '高级')], default='NORMAL', max_length=20, verbose_name='职级等级'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='department',
            field=models.CharField(blank=True, choices=[('SALES', '销售部门'), ('POC', '交付/实施/POC'), ('RND', '研发中心'), ('MARKETING', '市场部'), ('HR', '人力资源'), ('FINANCE', '财务部'), ('LAB', '实验室'), ('FUNCTION', '职能部门'), ('OTHER', '其他')], max_length=20, null=True, verbose_name='所属部门'),
        ),
        migrations.AlterField(
            model_name='departmentmodel',
            name='category',
            field=models.CharField(choices=[('SALES', '销售部门'), ('POC', '交付/实施/POC'), ('RND', '研发中心'), ('MARKETING', '市场部'), ('HR', '人力资源'), ('FINANCE', '财务部'), ('LAB', '实验室'), ('FUNCTION', '职能部门'), ('OTHER', '其他')], default='OTHER', max_length=20, verbose_name='部门性质'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='stage',
            field=models.CharField(choices=[('CONTACT', '接触阶段 (10%)'), ('REQ_ANALYSIS', '需求分析 (30%)'), ('INITIATION', '客户立项 (50%)'), ('BIDDING', '招采阶段 (70%)'), ('SIGNED', '已签约 (90%)'), ('DELIVERY', '交付实施 (95%)'), ('AFTER_SALES', '售后阶段 (100%)'), ('COMPLETED', '项目完成 (100%)'), ('SUSPENDED', '商机暂停 (0%)'), ('TERMINATED', '商机终止 (0%)'), ('WON', '赢单 (100%)'), ('LOST', '输单 (0%)')], default='CONTACT', max_length=20, verbose_name='阶段'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='job_level',
            field=models.CharField(blank=True, default='', help_text='例如：P5, P6, M1', max_length=20, verbose_name='职级(旧)'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='job_position',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='职位(旧)'),
        ),
        migrations.CreateModel(
            name='JobTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='岗位名称')),
                ('category', models.CharField(choices=[('MANAGEMENT', '管理'), ('RND', '研发'), ('SALES', '销售'), ('RESEARCHER', '研究员'), ('MARKETING', '市场'), ('OPERATION', '运营'), ('DESIGN', '设计'), ('SYSADMIN', '系统管理员'), ('ASSISTANT', '助理'), ('OTHER', '其他')], default='OTHER', max_length=20, verbose_name='岗位属性')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '岗位名称',
                'verbose_name_plural': '岗位名称配置',
                'unique_together': {('name', 'category')},
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='job_title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.jobtitle', verbose_name='岗位名称'),
        ),
    ]
