# Generated by Django 4.2.27 on 2026-01-06 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0073_userprofile_job_category_userprofile_job_rank_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='department',
            field=models.CharField(blank=True, choices=[('MANAGEMENT', '管理'), ('POC', 'POC'), ('RND', '研发'), ('LAB', '实验室'), ('FUNCTION', '职能'), ('SALES', '销售')], max_length=20, null=True, verbose_name='所属部门'),
        ),
        migrations.AlterField(
            model_name='departmentmodel',
            name='category',
            field=models.CharField(choices=[('MANAGEMENT', '管理'), ('POC', 'POC'), ('RND', '研发'), ('LAB', '实验室'), ('FUNCTION', '职能'), ('SALES', '销售')], default='FUNCTION', max_length=20, verbose_name='部门性质'),
        ),
    ]
