# Generated by Django 4.2.27 on 2026-01-06 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0074_alter_announcement_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='job_rank',
            field=models.CharField(blank=True, choices=[('ASSISTANT', '助理'), ('SPECIALIST', '专员'), ('SUPERVISOR', '主任'), ('MANAGER', '经理'), ('DIRECTOR', '总监'), ('DEPUTY_DIRECTOR', '副总监'), ('VP', '副总裁'), ('SVP', '高级副总裁'), ('AP', '助理总裁'), ('PRESIDENT', '总裁')], max_length=20, verbose_name='职级'),
        ),
    ]
