# Generated by Django 4.2.27 on 2026-01-07 15:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0075_alter_userprofile_job_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='删除时间'),
        ),
        migrations.AddField(
            model_name='project',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='是否已删除'),
        ),
        migrations.AlterField(
            model_name='aiconfiguration',
            name='provider',
            field=models.CharField(choices=[('OPENAI', 'OpenAI (及兼容接口)'), ('DEEPSEEK', 'DeepSeek'), ('GEMINI', 'Google Gemini'), ('OLLAMA', 'Ollama (Local)'), ('MOONSHOT', 'Kimi (Moonshot)'), ('ALIYUN', '通义千问'), ('GLM', '智谱GLM (OpenAPI兼容)'), ('OTHER', '其他')], default='DEEPSEEK', max_length=20, verbose_name='服务提供商'),
        ),
        migrations.CreateModel(
            name='ProjectDeleteLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200, verbose_name='原项目名称')),
                ('project_code', models.CharField(max_length=50, verbose_name='项目编号')),
                ('deleted_at', models.DateTimeField(auto_now_add=True, verbose_name='删除时间')),
                ('original_data', models.JSONField(verbose_name='原始数据备份')),
                ('is_restored', models.BooleanField(default=False, verbose_name='是否已恢复')),
                ('deleted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='删除人')),
            ],
            options={
                'verbose_name': '项目删除日志',
                'verbose_name_plural': '项目删除日志',
                'ordering': ['-deleted_at'],
            },
        ),
    ]
