# Generated by Django 4.2.27 on 2026-01-08 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0076_project_deleted_at_project_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='legal_representative',
            field=models.CharField(blank=True, max_length=50, verbose_name='法人代表'),
        ),
        migrations.AddField(
            model_name='customer',
            name='scale',
            field=models.CharField(blank=True, help_text='SMALL/MEDIUM/LARGE', max_length=20, verbose_name='规模'),
        ),
        migrations.AddField(
            model_name='customer',
            name='status',
            field=models.CharField(default='POTENTIAL', help_text='POTENTIAL/ACTIVE/LOST', max_length=20, verbose_name='状态'),
        ),
    ]
