# Generated by Django 4.2.27 on 2026-01-09 07:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0077_customer_legal_representative_customer_scale_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=50, verbose_name='版本号')),
                ('title', models.CharField(max_length=200, verbose_name='版本标题')),
                ('content', models.TextField(verbose_name='更新内容')),
                ('release_date', models.DateField(default=django.utils.timezone.now, verbose_name='发布日期')),
                ('is_current', models.BooleanField(default=False, verbose_name='是否当前版本')),
                ('status', models.CharField(default='RELEASED', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '系统版本',
                'verbose_name_plural': '系统版本',
                'ordering': ['-release_date'],
            },
        ),
        migrations.AddField(
            model_name='announcement',
            name='priority',
            field=models.CharField(default='MEDIUM', max_length=10, verbose_name='优先级'),
        ),
        migrations.AddField(
            model_name='competition',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='负责人'),
        ),
        migrations.AddField(
            model_name='competition',
            name='type',
            field=models.CharField(default='OTHER', max_length=20, verbose_name='赛事类型'),
        ),
        migrations.AddField(
            model_name='marketactivity',
            name='type',
            field=models.CharField(default='OTHER', max_length=20, verbose_name='活动类型'),
        ),
    ]
