<template>
  <div class="min-h-screen flex flex-col bg-gray-100 font-sans">
    <!-- Navbar -->
    <nav class="bg-white border-b border-gray-200 sticky top-0 z-50 shadow-sm">
      <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div class="flex justify-between h-16">
          <div class="flex items-center gap-4">
            <button @click="router.back()" class="text-gray-500 hover:text-gray-900 flex items-center gap-1 transition-colors" title="返回">
              <i data-lucide="arrow-left" class="w-5 h-5"></i> 返回
            </button>
            <div class="h-6 w-px bg-gray-200"></div>
            <div class="font-bold text-xl text-slate-800 tracking-tight">PROJECT TIMETABLE</div>
          </div>
          <div class="flex items-center text-sm text-gray-500 font-mono">
            {{ today }}
          </div>
        </div>
      </div>
    </nav>

    <main v-if="project" class="flex-1 w-full overflow-hidden flex flex-col bg-white shadow-xl m-4 rounded-xl border border-gray-200 mx-auto max-w-[95vw] h-[calc(100vh-6rem)]">
        <!-- Gantt Header (Months) -->
        <div class="flex border-b border-gray-200 bg-slate-50">
            <div class="w-72 flex-shrink-0 p-4 font-bold text-slate-700 border-r border-gray-200 flex items-center bg-slate-100">
                项目列表
            </div>
            <div class="flex-1 overflow-x-auto custom-scroll flex" ref="timelineHeader">
                <div v-for="month in months" :key="month.key" class="w-32 flex-shrink-0 border-r border-gray-200 text-center py-3 text-sm font-bold text-slate-600 bg-slate-50">
                    {{ month.label }}
                </div>
            </div>
        </div>

        <!-- Gantt Body -->
        <div class="flex-1 overflow-y-auto custom-scroll relative">
            <div v-if="Object.keys(groupedCards).length === 0" class="p-12 text-center text-gray-400">
                暂无启用状态的卡片数据
            </div>

            <div v-for="(groupCards, stageName) in groupedCards" :key="stageName" class="border-b border-gray-100">
                <!-- Group Header -->
                <div class="bg-blue-50 px-4 py-2 font-bold text-blue-800 text-sm flex items-center gap-2 sticky top-0 z-10 border-b border-blue-100 shadow-sm">
                    <span class="w-2 h-2 rounded-full" :class="getStageColor(stageName)"></span>
                    {{ stageName }} 
                    <span class="text-xs font-normal text-blue-600 bg-white/50 px-2 py-0.5 rounded ml-2">共 {{ groupCards.length }} 项</span>
                </div>

                <!-- Cards Rows -->
                <div v-for="card in groupCards" :key="card.id" class="flex hover:bg-slate-50 transition-colors group border-b border-dashed border-gray-100 last:border-b-0">
                    <!-- Left: Card Info -->
                    <div class="w-72 flex-shrink-0 p-3 border-r border-gray-200 flex flex-col justify-center min-h-[50px] relative bg-white group-hover:bg-slate-50 transition-colors z-10">
                        <div class="font-bold text-sm text-slate-800 line-clamp-1 mb-0.5" :title="card.title">{{ card.title }}</div>
                        <div class="text-[10px] font-mono text-slate-400 flex items-center gap-2">
                            <span>{{ card.extra_data?.code || card.id }}</span>
                        </div>
                    </div>

                    <!-- Right: Timeline Bar -->
                    <div class="flex-1 overflow-hidden relative">
                        <!-- Grid Lines (Background) -->
                        <div class="absolute inset-0 flex h-full" :style="{ transform: `translateX(-${scrollLeft}px)` }">
                            <div v-for="month in months" :key="month.key" class="w-32 flex-shrink-0 border-r border-dashed border-gray-100 h-full"></div>
                        </div>

                        <!-- Bar -->
                        <div class="absolute h-6 rounded-md top-1/2 -translate-y-1/2 text-xs text-white px-2 flex items-center shadow-sm whitespace-nowrap overflow-hidden transition-all hover:brightness-95 cursor-pointer z-0 font-medium"
                             :style="getBarStyle(card)"
                             :title="`${card.start_date} ~ ${card.deadline}`">
                            {{ card.title }}
                        </div>
                    </div>
                </div>
            </div>
        </div>
        
        <!-- Footer -->
        <div class="h-8 border-t border-gray-200 bg-slate-50 flex items-center justify-between px-4 text-[10px] text-slate-400 uppercase tracking-widest font-bold">
            <span></span>
            <span>Auto Generated by System</span>
        </div>
    </main>
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted, nextTick, computed, watch } from 'vue';
import { useRoute, useRouter } from 'vue-router';
import { createIcons, icons } from 'lucide';
import api from '../../api';

const route = useRoute();
const router = useRouter();
const projectId = route.params.id;

const project = ref<any>(null);
const cards = ref<any[]>([]);
const scrollLeft = ref(0);
const timelineHeader = ref<HTMLElement | null>(null);

const today = new Date().toISOString().slice(0, 10);

// Sync scroll
watch(timelineHeader, (el) => {
    if (el) {
        el.addEventListener('scroll', () => {
            scrollLeft.value = el.scrollLeft;
        });
    }
});

// 1. Generate Months (Last 2 months -> Next 12 months)
const months = computed(() => {
    const list = [];
    const now = new Date();
    const start = new Date(now.getFullYear(), now.getMonth() - 2, 1);
    
    for (let i = 0; i < 18; i++) {
        const d = new Date(start.getFullYear(), start.getMonth() + i, 1);
        list.push({
            key: `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`,
            label: `${d.getFullYear()}年${d.getMonth()+1}月`,
            date: d
        });
    }
    return list;
});

// 2. Group Cards by Stage
const groupedCards = computed(() => {
    const groups: Record<string, any[]> = {};
    const sorted = [...cards.value].sort((a, b) => (a.extra_data?.code || '').localeCompare(b.extra_data?.code || ''));
    
    sorted.forEach(c => {
        const code = c.extra_data?.code || '';
        const match = code.match(/-S(\d+)-/);
        let stage = '未分类阶段';
        if (match) {
            stage = `阶段 S${match[1]}`;
        } else if (code.includes('S1')) stage = '阶段 S1';
        else if (code.includes('S2')) stage = '阶段 S2';
        else if (code.includes('S3')) stage = '阶段 S3';
        
        if (!groups[stage]) groups[stage] = [];
        groups[stage]!.push(c);
    });
    
    // Sort keys
    return Object.keys(groups).sort().reduce((acc:Record<string, any[]>, key) => {
        acc[key] = groups[key] || [];
        return acc;
    }, {});
});

function getStageColor(name: string) {
    if (name.includes('S1')) return 'bg-blue-500';
    if (name.includes('S2')) return 'bg-green-500';
    if (name.includes('S3')) return 'bg-amber-400';
    return 'bg-gray-400';
}

function getBarStyle(card: any) {
    const m0 = months.value[0];
    if (!m0) return {};
    
    const timelineStart = m0.date.getTime();
    const monthMs = 30 * 24 * 60 * 60 * 1000; // approx
    const pxPerMs = 128 / monthMs;

    let start = card.start_date ? new Date(card.start_date).getTime() : new Date().getTime();
    let end = card.deadline ? new Date(card.deadline).getTime() : start + monthMs;

    if (end < start) end = start + monthMs;

    const offsetMs = start - timelineStart;
    const durationMs = end - start;

    const left = Math.max(0, offsetMs * pxPerMs);
    const width = Math.max(10, durationMs * pxPerMs);
    
    // Color Palette (Matching project_cards)
    let bg = '#3b82f6'; // Blue-500
    const code = card.extra_data?.code || '';
    
    if (code.includes('S1')) bg = '#3b82f6'; // Blue
    if (code.includes('S2')) bg = '#10b981'; // Emerald
    if (code.includes('S3')) bg = '#fbbf24'; // Amber
    if (card.status === 'DONE') bg = '#10b981'; 
    if (card.status === 'BLOCKED') bg = '#ef4444';

    return {
        left: `${left}px`,
        width: `${width}px`,
        backgroundColor: bg,
        transform: `translateX(-${scrollLeft.value}px)`
    };
}

async function loadData() {
    try {
        const pRes = await api.get(`/projects/${projectId}/`);
        project.value = pRes.data;

        const cRes = await api.get(`/project-cards/`, { 
            params: { 
                project: projectId, 
                is_active: true,
                limit: 1000
            } 
        });
        cards.value = cRes.data.results || [];
        
        await nextTick();
        createIcons({ icons });
        
        const header = timelineHeader.value;
        const body = header?.parentElement?.nextElementSibling as HTMLElement;
        if (header && body) {
            body.addEventListener('scroll', () => {
                header.scrollLeft = body.scrollLeft;
            });
             header.addEventListener('scroll', () => {
                body.scrollLeft = header.scrollLeft;
            });
        }
    } catch (e) {
        console.error("Failed to load timeline", e);
    }
}

onMounted(() => {
    loadData();
});
</script>

<style scoped>
.custom-scroll::-webkit-scrollbar { height: 8px; width: 8px; }
.custom-scroll::-webkit-scrollbar-track { background: #f1f5f9; }
.custom-scroll::-webkit-scrollbar-thumb { background: #cbd5e1; border-radius: 4px; }
.custom-scroll::-webkit-scrollbar-thumb:hover { background: #94a3b8; }
</style>